// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package workflows provides the Workflows binding
// (https://developers.cloudflare.com/workflows/).
package workflows

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Workflow
type Workflow struct{ v js.Value }

// WorkflowFromJS wraps a JS Workflow value.
func WorkflowFromJS(v js.Value) *Workflow { return &Workflow{v: v} }

// JSValue returns the underlying JS value.
func (x *Workflow) JSValue() js.Value { return x.v }

// NewWorkflow resolves the binding named bindingName from env.
func NewWorkflow(bindingName string) (*Workflow, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &Workflow{v: v}, nil
}

// Get Get a handle to an existing instance of the Workflow.
// @param id Id for the instance of this Workflow
// @returns A promise that resolves with a handle for the Instance
func (x *Workflow) Get(id string) (*WorkflowInstance, error) {
	p, err := jsrt.Call(x.v, "get", id)
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *WorkflowInstance
	ret = WorkflowInstanceFromJS(r)
	return ret, nil
}

// Create Create a new instance and return a handle to it. If a provided id exists, an error will be thrown.
// @param options Options when creating an instance including id and params
// @returns A promise that resolves with a handle for the Instance
func (x *Workflow) Create(options WorkflowInstanceCreateOptions) (*WorkflowInstance, error) {
	p, err := jsrt.Call(x.v, "create", options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *WorkflowInstance
	ret = WorkflowInstanceFromJS(r)
	return ret, nil
}

// DeleteBatch Delete a batch of Workflow instances and their stored state.
// `deleteBatch` is limited to 100 instances at a time. Duplicate IDs are deleted once.
// The result contains one entry for each input position; IDs that do not exist are returned as per-instance errors.
// @param instanceIds IDs of the Workflow instances to delete
// @returns A promise that resolves with the successfully deleted instances and any per-instance errors.
func (x *Workflow) DeleteBatch(instanceIds []string) (WorkflowBatchDeleteResult, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(instanceIds))
		for i, e := range instanceIds {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "deleteBatch", arg0)
	if err != nil {
		return WorkflowBatchDeleteResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return WorkflowBatchDeleteResult{}, err
	}
	var ret WorkflowBatchDeleteResult
	if tmp, err := workflowBatchDeleteResultFromJS(r); err != nil {
		return WorkflowBatchDeleteResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// WorkflowInstance
type WorkflowInstance struct{ v js.Value }

// WorkflowInstanceFromJS wraps a JS WorkflowInstance value.
func WorkflowInstanceFromJS(v js.Value) *WorkflowInstance { return &WorkflowInstance{v: v} }

// JSValue returns the underlying JS value.
func (x *WorkflowInstance) JSValue() js.Value { return x.v }

// ID
func (x *WorkflowInstance) ID() string {
	var ret string
	ret = x.v.Get("id").String()
	return ret
}

// Pause Pause the instance.
func (x *WorkflowInstance) Pause() error {
	p, err := jsrt.Call(x.v, "pause")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Resume Resume the instance. If it is already running, an error will be thrown.
func (x *WorkflowInstance) Resume() error {
	p, err := jsrt.Call(x.v, "resume")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Terminate Terminate the instance. If it is errored, terminated or complete, an error will be thrown.
// @param options Options for termination, including whether registered rollback handlers should run.
func (x *WorkflowInstance) Terminate(options WorkflowInstanceTerminateOptions) error {
	p, err := jsrt.Call(x.v, "terminate", options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Restart Restart the instance. Optionally restart from a specific step, preserving
// cached results for all steps before it.
// @param options Options for the restart, including an optional step to restart from.
func (x *WorkflowInstance) Restart(options WorkflowInstanceRestartOptions) error {
	p, err := jsrt.Call(x.v, "restart", options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Delete Delete the instance and its stored state.
func (x *WorkflowInstance) Delete() error {
	p, err := jsrt.Call(x.v, "delete")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Status Returns the current status of the instance.
func (x *WorkflowInstance) Status() (InstanceStatus, error) {
	p, err := jsrt.Call(x.v, "status")
	if err != nil {
		return InstanceStatus{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return InstanceStatus{}, err
	}
	var ret InstanceStatus
	if tmp, err := instanceStatusFromJS(r); err != nil {
		return InstanceStatus{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// WorkflowInstanceCreateOptions
type WorkflowInstanceCreateOptions struct {
	// An id for your Workflow instance. Must be unique within the Workflow.
	ID string `js:"id"`
	// The event payload the Workflow instance is triggered with
	Params js.Value `js:"params"`
	// The retention policy for Workflow instance.
	// Defaults to the maximum retention period available for the owner's account.
	Retention js.Value `js:"retention"`
	// A best-effort geographic placement preference for the Workflow instance.
	// See `WorkflowInstanceLocationHint` for supported regions.
	LocationHint WorkflowInstanceLocationHint `js:"locationHint"`
}

func workflowInstanceCreateOptionsFromJS(v js.Value) (WorkflowInstanceCreateOptions, error) {
	var out WorkflowInstanceCreateOptions
	{
		if s := v.Get("id"); !s.IsUndefined() && !s.IsNull() {
			out.ID = s.String()
		}
	}
	{
		if s := v.Get("params"); !s.IsUndefined() && !s.IsNull() {
			out.Params = s
		}
	}
	{
		if s := v.Get("retention"); !s.IsUndefined() && !s.IsNull() {
			out.Retention = s
		}
	}
	{
		if s := v.Get("locationHint"); !s.IsUndefined() && !s.IsNull() {
			out.LocationHint = WorkflowInstanceLocationHint(s.String())
		}
	}
	return out, nil
}

func (o WorkflowInstanceCreateOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if !jsrt.IsNil(o.Params) {
		obj.Set("params", o.Params)
	}
	if !jsrt.IsNil(o.Retention) {
		obj.Set("retention", o.Retention)
	}
	if o.LocationHint != "" {
		obj.Set("locationHint", string(o.LocationHint))
	}
	return obj
}

// WorkflowInstanceTerminateOptions
type WorkflowInstanceTerminateOptions struct {
	// If true, run registered rollback handlers before terminating the instance.
	// Only steps that registered rollback handlers are rolled back.
	Rollback bool `js:"rollback"`
}

func workflowInstanceTerminateOptionsFromJS(v js.Value) (WorkflowInstanceTerminateOptions, error) {
	var out WorkflowInstanceTerminateOptions
	{
		if s := v.Get("rollback"); !s.IsUndefined() && !s.IsNull() {
			out.Rollback = s.Bool()
		}
	}
	return out, nil
}

func (o WorkflowInstanceTerminateOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Rollback {
		obj.Set("rollback", o.Rollback)
	}
	return obj
}

// WorkflowInstanceRestartOptions
type WorkflowInstanceRestartOptions struct {
	// Restart from a specific step. If omitted, the instance restarts from the beginning.
	// The step must exist in the instance's execution history.
	From js.Value `js:"from"`
}

func workflowInstanceRestartOptionsFromJS(v js.Value) (WorkflowInstanceRestartOptions, error) {
	var out WorkflowInstanceRestartOptions
	{
		if s := v.Get("from"); !s.IsUndefined() && !s.IsNull() {
			out.From = s
		}
	}
	return out, nil
}

func (o WorkflowInstanceRestartOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.From) {
		obj.Set("from", o.From)
	}
	return obj
}

// WorkflowInstanceLocationHint Geographic regions supported when creating a Workflow instance.
// Location hints are best-effort placement preferences.
type WorkflowInstanceLocationHint string

const (
	WorkflowInstanceLocationHintWnam   WorkflowInstanceLocationHint = "wnam"
	WorkflowInstanceLocationHintEnam   WorkflowInstanceLocationHint = "enam"
	WorkflowInstanceLocationHintSam    WorkflowInstanceLocationHint = "sam"
	WorkflowInstanceLocationHintWeur   WorkflowInstanceLocationHint = "weur"
	WorkflowInstanceLocationHintEeur   WorkflowInstanceLocationHint = "eeur"
	WorkflowInstanceLocationHintApac   WorkflowInstanceLocationHint = "apac"
	WorkflowInstanceLocationHintApacNe WorkflowInstanceLocationHint = "apac-ne"
	WorkflowInstanceLocationHintApacSe WorkflowInstanceLocationHint = "apac-se"
	WorkflowInstanceLocationHintOc     WorkflowInstanceLocationHint = "oc"
	WorkflowInstanceLocationHintAfr    WorkflowInstanceLocationHint = "afr"
	WorkflowInstanceLocationHintMe     WorkflowInstanceLocationHint = "me"
)

// WorkflowBatchDeleteResult
type WorkflowBatchDeleteResult struct {
	Deleted []js.Value `js:"deleted"`
	Errors  []js.Value `js:"errors"`
}

func workflowBatchDeleteResultFromJS(v js.Value) (WorkflowBatchDeleteResult, error) {
	var out WorkflowBatchDeleteResult
	{
		out.Deleted = make([]js.Value, v.Get("deleted").Length())
		for i := range out.Deleted {
			out.Deleted[i] = v.Get("deleted").Index(i)
		}
	}
	{
		out.Errors = make([]js.Value, v.Get("errors").Length())
		for i := range out.Errors {
			out.Errors[i] = v.Get("errors").Index(i)
		}
	}
	return out, nil
}

func (o WorkflowBatchDeleteResult) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Deleted) > 0 {
		arr := js.Global().Get("Array").New(len(o.Deleted))
		for i, e := range o.Deleted {
			arr.SetIndex(i, e)
		}
		obj.Set("deleted", arr)
	}
	if len(o.Errors) > 0 {
		arr := js.Global().Get("Array").New(len(o.Errors))
		for i, e := range o.Errors {
			arr.SetIndex(i, e)
		}
		obj.Set("errors", arr)
	}
	return obj
}

// InstanceStatus
type InstanceStatus struct {
	Status string   `js:"status"`
	Error  js.Value `js:"error"`
	Output js.Value `js:"output"`
}

func instanceStatusFromJS(v js.Value) (InstanceStatus, error) {
	var out InstanceStatus
	{
		out.Status = v.Get("status").String()
	}
	{
		if s := v.Get("error"); !s.IsUndefined() && !s.IsNull() {
			out.Error = s
		}
	}
	{
		if s := v.Get("output"); !s.IsUndefined() && !s.IsNull() {
			out.Output = s
		}
	}
	return out, nil
}

func (o InstanceStatus) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Status != "" {
		obj.Set("status", o.Status)
	}
	if !jsrt.IsNil(o.Error) {
		obj.Set("error", o.Error)
	}
	if !jsrt.IsNil(o.Output) {
		obj.Set("output", o.Output)
	}
	return obj
}
