// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package kv provides the Workers KV binding
// (https://developers.cloudflare.com/kv/).
//
// KVNamespace.get and .getWithMetadata are each overloaded on a "type"
// discriminant, either as a plain literal "text"/"json"/"arrayBuffer"/
// "stream" argument, or as an options object carrying the same value as
// its "type" field (KVNamespaceGetOptions<"text"> etc., needed to also
// pass cacheTtl). This package uses the options-object overloads, so it
// exposes GetText/GetJSON/GetBytes/GetStream (and the WithMetadata
// variants) each taking a KVNamespaceGetOptions; the caller (L2) is
// responsible for setting its Type field to the matching value. The json
// variants return js.Value rather than a decoded value, since the JSON
// shape is caller-defined (KVNamespace<Key>'s "get<ExpectedValue>(...,
// "json")" generic has no default to map to a concrete Go type).
package kv

import (
	"io"
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// KVNamespace
type KVNamespace struct{ v js.Value }

// KVNamespaceFromJS wraps a JS KVNamespace value.
func KVNamespaceFromJS(v js.Value) *KVNamespace { return &KVNamespace{v: v} }

// JSValue returns the underlying JS value.
func (x *KVNamespace) JSValue() js.Value { return x.v }

// NewKVNamespace resolves the binding named bindingName from env.
func NewKVNamespace(bindingName string) (*KVNamespace, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &KVNamespace{v: v}, nil
}

// GetText
func (x *KVNamespace) GetText(key string, options KVNamespaceGetOptions) (*string, error) {
	p, err := jsrt.Call(x.v, "get", key, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *string
	if !jsrt.IsNil(r) {
		var val string
		val = r.String()
		ret = &val
	}
	return ret, nil
}

// GetJSON
func (x *KVNamespace) GetJSON(key string, options KVNamespaceGetOptions) (js.Value, error) {
	p, err := jsrt.Call(x.v, "get", key, options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// GetBytes
func (x *KVNamespace) GetBytes(key string, options KVNamespaceGetOptions) ([]byte, error) {
	p, err := jsrt.Call(x.v, "get", key, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret []byte
	if !jsrt.IsNil(r) {
		ret = jsrt.BytesFromJS(r)
	}
	return ret, nil
}

// GetStream
func (x *KVNamespace) GetStream(key string, options KVNamespaceGetOptions) (io.ReadCloser, error) {
	p, err := jsrt.Call(x.v, "get", key, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret io.ReadCloser
	if !jsrt.IsNil(r) {
		ret = jsrt.ReadCloser(r)
	}
	return ret, nil
}

// List
func (x *KVNamespace) List(options KVNamespaceListOptions) (KVNamespaceListResult, error) {
	p, err := jsrt.Call(x.v, "list", options.toJS())
	if err != nil {
		return KVNamespaceListResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return KVNamespaceListResult{}, err
	}
	var ret KVNamespaceListResult
	if tmp, err := kVNamespaceListResultFromJS(r); err != nil {
		return KVNamespaceListResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Put
func (x *KVNamespace) Put(key string, value js.Value, options KVNamespacePutOptions) error {
	p, err := jsrt.Call(x.v, "put", key, value, options.toJS())
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// GetTextWithMetadata
func (x *KVNamespace) GetTextWithMetadata(key string, options KVNamespaceGetOptions) (KVNamespaceGetWithMetadataResult, error) {
	p, err := jsrt.Call(x.v, "getWithMetadata", key, options.toJS())
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	var ret KVNamespaceGetWithMetadataResult
	if tmp, err := kVNamespaceGetWithMetadataResultFromJS(r); err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// GetJSONWithMetadata
func (x *KVNamespace) GetJSONWithMetadata(key string, options KVNamespaceGetOptions) (KVNamespaceGetWithMetadataResult, error) {
	p, err := jsrt.Call(x.v, "getWithMetadata", key, options.toJS())
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	var ret KVNamespaceGetWithMetadataResult
	if tmp, err := kVNamespaceGetWithMetadataResultFromJS(r); err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// GetBytesWithMetadata
func (x *KVNamespace) GetBytesWithMetadata(key string, options KVNamespaceGetOptions) (KVNamespaceGetWithMetadataResult, error) {
	p, err := jsrt.Call(x.v, "getWithMetadata", key, options.toJS())
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	var ret KVNamespaceGetWithMetadataResult
	if tmp, err := kVNamespaceGetWithMetadataResultFromJS(r); err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// GetStreamWithMetadata
func (x *KVNamespace) GetStreamWithMetadata(key string, options KVNamespaceGetOptions) (KVNamespaceGetWithMetadataResult, error) {
	p, err := jsrt.Call(x.v, "getWithMetadata", key, options.toJS())
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	}
	var ret KVNamespaceGetWithMetadataResult
	if tmp, err := kVNamespaceGetWithMetadataResultFromJS(r); err != nil {
		return KVNamespaceGetWithMetadataResult{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Delete
func (x *KVNamespace) Delete(key string) error {
	p, err := jsrt.Call(x.v, "delete", key)
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// KVNamespaceGetOptions
type KVNamespaceGetOptions struct {
	Type     string `js:"type"`
	CacheTTL int    `js:"cacheTtl"`
}

func kVNamespaceGetOptionsFromJS(v js.Value) (KVNamespaceGetOptions, error) {
	var out KVNamespaceGetOptions
	{
		out.Type = v.Get("type").String()
	}
	{
		if s := v.Get("cacheTtl"); !s.IsUndefined() && !s.IsNull() {
			out.CacheTTL = s.Int()
		}
	}
	return out, nil
}

func (o KVNamespaceGetOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Type != "" {
		obj.Set("type", o.Type)
	}
	if o.CacheTTL != 0 {
		obj.Set("cacheTtl", o.CacheTTL)
	}
	return obj
}

// KVNamespacePutOptions
type KVNamespacePutOptions struct {
	Expiration    int      `js:"expiration"`
	ExpirationTTL int      `js:"expirationTtl"`
	Metadata      js.Value `js:"metadata"`
}

func kVNamespacePutOptionsFromJS(v js.Value) (KVNamespacePutOptions, error) {
	var out KVNamespacePutOptions
	{
		if s := v.Get("expiration"); !s.IsUndefined() && !s.IsNull() {
			out.Expiration = s.Int()
		}
	}
	{
		if s := v.Get("expirationTtl"); !s.IsUndefined() && !s.IsNull() {
			out.ExpirationTTL = s.Int()
		}
	}
	{
		if s := v.Get("metadata"); !s.IsUndefined() && !s.IsNull() {
			out.Metadata = s
		}
	}
	return out, nil
}

func (o KVNamespacePutOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Expiration != 0 {
		obj.Set("expiration", o.Expiration)
	}
	if o.ExpirationTTL != 0 {
		obj.Set("expirationTtl", o.ExpirationTTL)
	}
	if !jsrt.IsNil(o.Metadata) {
		obj.Set("metadata", o.Metadata)
	}
	return obj
}

// KVNamespaceListOptions
type KVNamespaceListOptions struct {
	Limit  float64 `js:"limit"`
	Prefix string  `js:"prefix"`
	Cursor string  `js:"cursor"`
}

func kVNamespaceListOptionsFromJS(v js.Value) (KVNamespaceListOptions, error) {
	var out KVNamespaceListOptions
	{
		if s := v.Get("limit"); !s.IsUndefined() && !s.IsNull() {
			out.Limit = s.Float()
		}
	}
	{
		if s := v.Get("prefix"); !s.IsUndefined() && !s.IsNull() {
			out.Prefix = s.String()
		}
	}
	{
		if s := v.Get("cursor"); !s.IsUndefined() && !s.IsNull() {
			out.Cursor = s.String()
		}
	}
	return out, nil
}

func (o KVNamespaceListOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Limit != 0 {
		obj.Set("limit", o.Limit)
	}
	if o.Prefix != "" {
		obj.Set("prefix", o.Prefix)
	}
	if o.Cursor != "" {
		obj.Set("cursor", o.Cursor)
	}
	return obj
}

// KVNamespaceListResult
type KVNamespaceListResult struct {
	ListComplete bool                 `js:"list_complete"`
	Keys         []KVNamespaceListKey `js:"keys"`
	Cursor       string               `js:"cursor"`
	CacheStatus  string               `js:"cacheStatus"`
}

func kVNamespaceListResultFromJS(v js.Value) (KVNamespaceListResult, error) {
	var out KVNamespaceListResult
	{
		out.ListComplete = v.Get("list_complete").Bool()
	}
	{
		out.Keys = make([]KVNamespaceListKey, v.Get("keys").Length())
		for i := range out.Keys {
			if tmp, err := kVNamespaceListKeyFromJS(v.Get("keys").Index(i)); err != nil {
				return KVNamespaceListResult{}, err
			} else {
				out.Keys[i] = tmp
			}
		}
	}
	{
		if s := v.Get("cursor"); !s.IsUndefined() && !s.IsNull() {
			out.Cursor = s.String()
		}
	}
	{
		if s := v.Get("cacheStatus"); !s.IsUndefined() && !s.IsNull() {
			out.CacheStatus = s.String()
		}
	}
	return out, nil
}

func (o KVNamespaceListResult) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ListComplete {
		obj.Set("list_complete", o.ListComplete)
	}
	if len(o.Keys) > 0 {
		arr := js.Global().Get("Array").New(len(o.Keys))
		for i, e := range o.Keys {
			arr.SetIndex(i, e.toJS())
		}
		obj.Set("keys", arr)
	}
	if o.Cursor != "" {
		obj.Set("cursor", o.Cursor)
	}
	if o.CacheStatus != "" {
		obj.Set("cacheStatus", o.CacheStatus)
	}
	return obj
}

// KVNamespaceListKey
type KVNamespaceListKey struct {
	Name       string   `js:"name"`
	Expiration float64  `js:"expiration"`
	Metadata   js.Value `js:"metadata"`
}

func kVNamespaceListKeyFromJS(v js.Value) (KVNamespaceListKey, error) {
	var out KVNamespaceListKey
	{
		out.Name = v.Get("name").String()
	}
	{
		if s := v.Get("expiration"); !s.IsUndefined() && !s.IsNull() {
			out.Expiration = s.Float()
		}
	}
	{
		if s := v.Get("metadata"); !s.IsUndefined() && !s.IsNull() {
			out.Metadata = s
		}
	}
	return out, nil
}

func (o KVNamespaceListKey) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Name != "" {
		obj.Set("name", o.Name)
	}
	if o.Expiration != 0 {
		obj.Set("expiration", o.Expiration)
	}
	if !jsrt.IsNil(o.Metadata) {
		obj.Set("metadata", o.Metadata)
	}
	return obj
}

// KVNamespaceGetWithMetadataResult
type KVNamespaceGetWithMetadataResult struct {
	Value       js.Value `js:"value"`
	Metadata    js.Value `js:"metadata"`
	CacheStatus string   `js:"cacheStatus"`
}

func kVNamespaceGetWithMetadataResultFromJS(v js.Value) (KVNamespaceGetWithMetadataResult, error) {
	var out KVNamespaceGetWithMetadataResult
	{
		if s := v.Get("value"); !s.IsUndefined() && !s.IsNull() {
			out.Value = s
		}
	}
	{
		if s := v.Get("metadata"); !s.IsUndefined() && !s.IsNull() {
			out.Metadata = s
		}
	}
	{
		if s := v.Get("cacheStatus"); !s.IsUndefined() && !s.IsNull() {
			out.CacheStatus = s.String()
		}
	}
	return out, nil
}

func (o KVNamespaceGetWithMetadataResult) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.Value) {
		obj.Set("value", o.Value)
	}
	if !jsrt.IsNil(o.Metadata) {
		obj.Set("metadata", o.Metadata)
	}
	if o.CacheStatus != "" {
		obj.Set("cacheStatus", o.CacheStatus)
	}
	return obj
}
