// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package r2 provides the R2 bucket binding
// (https://developers.cloudflare.com/r2/).
//
// R2Bucket.get and .put are each overloaded on whether "options" carries an
// extra onlyIf-as-Headers field cfgen can't express generically; only the
// plain (R2GetOptions/R2PutOptions) overload is generated, as Get/Put.
package r2

import (
	"io"
	"net/http"
	"syscall/js"
	"time"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// R2Bucket
type R2Bucket struct{ v js.Value }

// R2BucketFromJS wraps a JS R2Bucket value.
func R2BucketFromJS(v js.Value) *R2Bucket { return &R2Bucket{v: v} }

// JSValue returns the underlying JS value.
func (x *R2Bucket) JSValue() js.Value { return x.v }

// NewR2Bucket resolves the binding named bindingName from env.
func NewR2Bucket(bindingName string) (*R2Bucket, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &R2Bucket{v: v}, nil
}

// Head
func (x *R2Bucket) Head(key string) (*R2Object, error) {
	p, err := jsrt.Call(x.v, "head", key)
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *R2Object
	if !jsrt.IsNil(r) {
		ret = R2ObjectFromJS(r)
	}
	return ret, nil
}

// Get
func (x *R2Bucket) Get(key string, options R2GetOptions) (*R2ObjectBody, error) {
	p, err := jsrt.Call(x.v, "get", key, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *R2ObjectBody
	if !jsrt.IsNil(r) {
		ret = R2ObjectBodyFromJS(r)
	}
	return ret, nil
}

// Put
func (x *R2Bucket) Put(key string, value js.Value, options R2PutOptions) (*R2Object, error) {
	p, err := jsrt.Call(x.v, "put", key, value, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *R2Object
	ret = R2ObjectFromJS(r)
	return ret, nil
}

// CreateMultipartUpload
func (x *R2Bucket) CreateMultipartUpload(key string, options R2MultipartOptions) (*R2MultipartUpload, error) {
	p, err := jsrt.Call(x.v, "createMultipartUpload", key, options.toJS())
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *R2MultipartUpload
	ret = R2MultipartUploadFromJS(r)
	return ret, nil
}

// ResumeMultipartUpload
func (x *R2Bucket) ResumeMultipartUpload(key string, uploadId string) (*R2MultipartUpload, error) {
	r, err := jsrt.Call(x.v, "resumeMultipartUpload", key, uploadId)
	if err != nil {
		return nil, err
	}
	var ret *R2MultipartUpload
	ret = R2MultipartUploadFromJS(r)
	return ret, nil
}

// Delete
func (x *R2Bucket) Delete(keys []string) error {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(keys))
		for i, e := range keys {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "delete", arg0)
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// List
func (x *R2Bucket) List(options R2ListOptions) (R2Objects, error) {
	p, err := jsrt.Call(x.v, "list", options.toJS())
	if err != nil {
		return R2Objects{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return R2Objects{}, err
	}
	var ret R2Objects
	if tmp, err := r2ObjectsFromJS(r); err != nil {
		return R2Objects{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// R2Object
type R2Object struct{ v js.Value }

// R2ObjectFromJS wraps a JS R2Object value.
func R2ObjectFromJS(v js.Value) *R2Object { return &R2Object{v: v} }

// JSValue returns the underlying JS value.
func (x *R2Object) JSValue() js.Value { return x.v }

// Key
func (x *R2Object) Key() string {
	var ret string
	ret = x.v.Get("key").String()
	return ret
}

// Version
func (x *R2Object) Version() string {
	var ret string
	ret = x.v.Get("version").String()
	return ret
}

// Size
func (x *R2Object) Size() int {
	var ret int
	ret = x.v.Get("size").Int()
	return ret
}

// Etag
func (x *R2Object) Etag() string {
	var ret string
	ret = x.v.Get("etag").String()
	return ret
}

// HTTPEtag
func (x *R2Object) HTTPEtag() string {
	var ret string
	ret = x.v.Get("httpEtag").String()
	return ret
}

// Checksums
func (x *R2Object) Checksums() *R2Checksums {
	var ret *R2Checksums
	ret = R2ChecksumsFromJS(x.v.Get("checksums"))
	return ret
}

// Uploaded
func (x *R2Object) Uploaded() time.Time {
	var ret time.Time
	ret = jsrt.DateToTime(x.v.Get("uploaded"))
	return ret
}

// HTTPMetadata
func (x *R2Object) HTTPMetadata() R2HTTPMetadata {
	var ret R2HTTPMetadata
	if s := x.v.Get("httpMetadata"); !s.IsUndefined() && !s.IsNull() {
		if tmp, err := r2HTTPMetadataFromJS(s); err == nil {
			ret = tmp
		}
	}
	return ret
}

// CustomMetadata
func (x *R2Object) CustomMetadata() map[string]string {
	var ret map[string]string
	if s := x.v.Get("customMetadata"); !s.IsUndefined() && !s.IsNull() {
		ret = make(map[string]string)
		keys := js.Global().Get("Object").Call("keys", s)
		for i := 0; i < keys.Length(); i++ {
			k := keys.Index(i).String()
			var vv string
			vv = s.Get(k).String()
			ret[k] = vv
		}
	}
	return ret
}

// Range
func (x *R2Object) Range() R2Range {
	var ret R2Range
	if s := x.v.Get("range"); !s.IsUndefined() && !s.IsNull() {
		if tmp, err := r2RangeFromJS(s); err == nil {
			ret = tmp
		}
	}
	return ret
}

// StorageClass
func (x *R2Object) StorageClass() string {
	var ret string
	ret = x.v.Get("storageClass").String()
	return ret
}

// SsecKeyMD5
func (x *R2Object) SsecKeyMD5() string {
	var ret string
	if s := x.v.Get("ssecKeyMd5"); !s.IsUndefined() && !s.IsNull() {
		ret = s.String()
	}
	return ret
}

// WriteHTTPMetadata
func (x *R2Object) WriteHTTPMetadata(headers http.Header) error {
	_, err := jsrt.Call(x.v, "writeHttpMetadata", jsrt.HeadersToJS(headers))
	return err
}

// R2ObjectBody
type R2ObjectBody struct{ v js.Value }

// R2ObjectBodyFromJS wraps a JS R2ObjectBody value.
func R2ObjectBodyFromJS(v js.Value) *R2ObjectBody { return &R2ObjectBody{v: v} }

// JSValue returns the underlying JS value.
func (x *R2ObjectBody) JSValue() js.Value { return x.v }

// Key
func (x *R2ObjectBody) Key() string {
	var ret string
	ret = x.v.Get("key").String()
	return ret
}

// Version
func (x *R2ObjectBody) Version() string {
	var ret string
	ret = x.v.Get("version").String()
	return ret
}

// Size
func (x *R2ObjectBody) Size() int {
	var ret int
	ret = x.v.Get("size").Int()
	return ret
}

// Etag
func (x *R2ObjectBody) Etag() string {
	var ret string
	ret = x.v.Get("etag").String()
	return ret
}

// HTTPEtag
func (x *R2ObjectBody) HTTPEtag() string {
	var ret string
	ret = x.v.Get("httpEtag").String()
	return ret
}

// Checksums
func (x *R2ObjectBody) Checksums() *R2Checksums {
	var ret *R2Checksums
	ret = R2ChecksumsFromJS(x.v.Get("checksums"))
	return ret
}

// Uploaded
func (x *R2ObjectBody) Uploaded() time.Time {
	var ret time.Time
	ret = jsrt.DateToTime(x.v.Get("uploaded"))
	return ret
}

// HTTPMetadata
func (x *R2ObjectBody) HTTPMetadata() R2HTTPMetadata {
	var ret R2HTTPMetadata
	if s := x.v.Get("httpMetadata"); !s.IsUndefined() && !s.IsNull() {
		if tmp, err := r2HTTPMetadataFromJS(s); err == nil {
			ret = tmp
		}
	}
	return ret
}

// CustomMetadata
func (x *R2ObjectBody) CustomMetadata() map[string]string {
	var ret map[string]string
	if s := x.v.Get("customMetadata"); !s.IsUndefined() && !s.IsNull() {
		ret = make(map[string]string)
		keys := js.Global().Get("Object").Call("keys", s)
		for i := 0; i < keys.Length(); i++ {
			k := keys.Index(i).String()
			var vv string
			vv = s.Get(k).String()
			ret[k] = vv
		}
	}
	return ret
}

// Range
func (x *R2ObjectBody) Range() R2Range {
	var ret R2Range
	if s := x.v.Get("range"); !s.IsUndefined() && !s.IsNull() {
		if tmp, err := r2RangeFromJS(s); err == nil {
			ret = tmp
		}
	}
	return ret
}

// StorageClass
func (x *R2ObjectBody) StorageClass() string {
	var ret string
	ret = x.v.Get("storageClass").String()
	return ret
}

// SsecKeyMD5
func (x *R2ObjectBody) SsecKeyMD5() string {
	var ret string
	if s := x.v.Get("ssecKeyMd5"); !s.IsUndefined() && !s.IsNull() {
		ret = s.String()
	}
	return ret
}

// WriteHTTPMetadata
func (x *R2ObjectBody) WriteHTTPMetadata(headers http.Header) error {
	_, err := jsrt.Call(x.v, "writeHttpMetadata", jsrt.HeadersToJS(headers))
	return err
}

// Body
func (x *R2ObjectBody) Body() io.ReadCloser {
	var ret io.ReadCloser
	ret = jsrt.ReadCloser(x.v.Get("body"))
	return ret
}

// BodyUsed
func (x *R2ObjectBody) BodyUsed() bool {
	var ret bool
	ret = x.v.Get("bodyUsed").Bool()
	return ret
}

// ArrayBuffer
func (x *R2ObjectBody) ArrayBuffer() ([]byte, error) {
	p, err := jsrt.Call(x.v, "arrayBuffer")
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret []byte
	ret = jsrt.BytesFromJS(r)
	return ret, nil
}

// Bytes
func (x *R2ObjectBody) Bytes() ([]byte, error) {
	p, err := jsrt.Call(x.v, "bytes")
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret []byte
	ret = jsrt.BytesFromJS(r)
	return ret, nil
}

// Text
func (x *R2ObjectBody) Text() (string, error) {
	p, err := jsrt.Call(x.v, "text")
	if err != nil {
		return "", err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return "", err
	}
	var ret string
	ret = r.String()
	return ret, nil
}

// R2Objects
type R2Objects struct {
	Objects           []*R2Object `js:"objects"`
	DelimitedPrefixes []string    `js:"delimitedPrefixes"`
	Truncated         bool        `js:"truncated"`
	Cursor            string      `js:"cursor"`
}

func r2ObjectsFromJS(v js.Value) (R2Objects, error) {
	var out R2Objects
	{
		out.Objects = make([]*R2Object, v.Get("objects").Length())
		for i := range out.Objects {
			out.Objects[i] = R2ObjectFromJS(v.Get("objects").Index(i))
		}
	}
	{
		out.DelimitedPrefixes = make([]string, v.Get("delimitedPrefixes").Length())
		for i := range out.DelimitedPrefixes {
			out.DelimitedPrefixes[i] = v.Get("delimitedPrefixes").Index(i).String()
		}
	}
	{
		out.Truncated = v.Get("truncated").Bool()
	}
	{
		if s := v.Get("cursor"); !s.IsUndefined() && !s.IsNull() {
			out.Cursor = s.String()
		}
	}
	return out, nil
}

func (o R2Objects) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Objects) > 0 {
		arr := js.Global().Get("Array").New(len(o.Objects))
		for i, e := range o.Objects {
			arr.SetIndex(i, e.JSValue())
		}
		obj.Set("objects", arr)
	}
	if len(o.DelimitedPrefixes) > 0 {
		arr := js.Global().Get("Array").New(len(o.DelimitedPrefixes))
		for i, e := range o.DelimitedPrefixes {
			arr.SetIndex(i, e)
		}
		obj.Set("delimitedPrefixes", arr)
	}
	if o.Truncated {
		obj.Set("truncated", o.Truncated)
	}
	if o.Cursor != "" {
		obj.Set("cursor", o.Cursor)
	}
	return obj
}

// R2GetOptions
type R2GetOptions struct {
	OnlyIf  *R2Conditional `js:"onlyIf"`
	Range   *R2Range       `js:"range"`
	SsecKey string         `js:"ssecKey"`
}

func r2GetOptionsFromJS(v js.Value) (R2GetOptions, error) {
	var out R2GetOptions
	{
		if !jsrt.IsNil(v.Get("onlyIf")) {
			var val R2Conditional
			if tmp, err := r2ConditionalFromJS(v.Get("onlyIf")); err != nil {
				return R2GetOptions{}, err
			} else {
				val = tmp
			}
			out.OnlyIf = &val
		}
	}
	{
		if !jsrt.IsNil(v.Get("range")) {
			var val R2Range
			if tmp, err := r2RangeFromJS(v.Get("range")); err != nil {
				return R2GetOptions{}, err
			} else {
				val = tmp
			}
			out.Range = &val
		}
	}
	{
		if s := v.Get("ssecKey"); !s.IsUndefined() && !s.IsNull() {
			out.SsecKey = s.String()
		}
	}
	return out, nil
}

func (o R2GetOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.OnlyIf != nil {
		obj.Set("onlyIf", (*o.OnlyIf).toJS())
	}
	if o.Range != nil {
		obj.Set("range", (*o.Range).toJS())
	}
	if o.SsecKey != "" {
		obj.Set("ssecKey", o.SsecKey)
	}
	return obj
}

// R2PutOptions
type R2PutOptions struct {
	OnlyIf         *R2Conditional    `js:"onlyIf"`
	HTTPMetadata   *R2HTTPMetadata   `js:"httpMetadata"`
	CustomMetadata map[string]string `js:"customMetadata"`
	MD5            string            `js:"md5"`
	Sha1           string            `js:"sha1"`
	Sha256         string            `js:"sha256"`
	Sha384         string            `js:"sha384"`
	Sha512         string            `js:"sha512"`
	StorageClass   string            `js:"storageClass"`
	SsecKey        string            `js:"ssecKey"`
}

func r2PutOptionsFromJS(v js.Value) (R2PutOptions, error) {
	var out R2PutOptions
	{
		if !jsrt.IsNil(v.Get("onlyIf")) {
			var val R2Conditional
			if tmp, err := r2ConditionalFromJS(v.Get("onlyIf")); err != nil {
				return R2PutOptions{}, err
			} else {
				val = tmp
			}
			out.OnlyIf = &val
		}
	}
	{
		if !jsrt.IsNil(v.Get("httpMetadata")) {
			var val R2HTTPMetadata
			if tmp, err := r2HTTPMetadataFromJS(v.Get("httpMetadata")); err != nil {
				return R2PutOptions{}, err
			} else {
				val = tmp
			}
			out.HTTPMetadata = &val
		}
	}
	{
		if s := v.Get("customMetadata"); !s.IsUndefined() && !s.IsNull() {
			out.CustomMetadata = make(map[string]string)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				var vv string
				vv = s.Get(k).String()
				out.CustomMetadata[k] = vv
			}
		}
	}
	{
		if s := v.Get("md5"); !s.IsUndefined() && !s.IsNull() {
			out.MD5 = s.String()
		}
	}
	{
		if s := v.Get("sha1"); !s.IsUndefined() && !s.IsNull() {
			out.Sha1 = s.String()
		}
	}
	{
		if s := v.Get("sha256"); !s.IsUndefined() && !s.IsNull() {
			out.Sha256 = s.String()
		}
	}
	{
		if s := v.Get("sha384"); !s.IsUndefined() && !s.IsNull() {
			out.Sha384 = s.String()
		}
	}
	{
		if s := v.Get("sha512"); !s.IsUndefined() && !s.IsNull() {
			out.Sha512 = s.String()
		}
	}
	{
		if s := v.Get("storageClass"); !s.IsUndefined() && !s.IsNull() {
			out.StorageClass = s.String()
		}
	}
	{
		if s := v.Get("ssecKey"); !s.IsUndefined() && !s.IsNull() {
			out.SsecKey = s.String()
		}
	}
	return out, nil
}

func (o R2PutOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.OnlyIf != nil {
		obj.Set("onlyIf", (*o.OnlyIf).toJS())
	}
	if o.HTTPMetadata != nil {
		obj.Set("httpMetadata", (*o.HTTPMetadata).toJS())
	}
	if len(o.CustomMetadata) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.CustomMetadata {
			m.Set(k, v)
		}
		obj.Set("customMetadata", m)
	}
	if o.MD5 != "" {
		obj.Set("md5", o.MD5)
	}
	if o.Sha1 != "" {
		obj.Set("sha1", o.Sha1)
	}
	if o.Sha256 != "" {
		obj.Set("sha256", o.Sha256)
	}
	if o.Sha384 != "" {
		obj.Set("sha384", o.Sha384)
	}
	if o.Sha512 != "" {
		obj.Set("sha512", o.Sha512)
	}
	if o.StorageClass != "" {
		obj.Set("storageClass", o.StorageClass)
	}
	if o.SsecKey != "" {
		obj.Set("ssecKey", o.SsecKey)
	}
	return obj
}

// R2ListOptions
type R2ListOptions struct {
	Limit      float64  `js:"limit"`
	Prefix     string   `js:"prefix"`
	Cursor     string   `js:"cursor"`
	Delimiter  string   `js:"delimiter"`
	StartAfter string   `js:"startAfter"`
	Include    []string `js:"include"`
}

func r2ListOptionsFromJS(v js.Value) (R2ListOptions, error) {
	var out R2ListOptions
	{
		if s := v.Get("limit"); !s.IsUndefined() && !s.IsNull() {
			out.Limit = s.Float()
		}
	}
	{
		if s := v.Get("prefix"); !s.IsUndefined() && !s.IsNull() {
			out.Prefix = s.String()
		}
	}
	{
		if s := v.Get("cursor"); !s.IsUndefined() && !s.IsNull() {
			out.Cursor = s.String()
		}
	}
	{
		if s := v.Get("delimiter"); !s.IsUndefined() && !s.IsNull() {
			out.Delimiter = s.String()
		}
	}
	{
		if s := v.Get("startAfter"); !s.IsUndefined() && !s.IsNull() {
			out.StartAfter = s.String()
		}
	}
	{
		if s := v.Get("include"); !s.IsUndefined() && !s.IsNull() {
			out.Include = make([]string, s.Length())
			for i := range out.Include {
				out.Include[i] = s.Index(i).String()
			}
		}
	}
	return out, nil
}

func (o R2ListOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Limit != 0 {
		obj.Set("limit", o.Limit)
	}
	if o.Prefix != "" {
		obj.Set("prefix", o.Prefix)
	}
	if o.Cursor != "" {
		obj.Set("cursor", o.Cursor)
	}
	if o.Delimiter != "" {
		obj.Set("delimiter", o.Delimiter)
	}
	if o.StartAfter != "" {
		obj.Set("startAfter", o.StartAfter)
	}
	if len(o.Include) > 0 {
		arr := js.Global().Get("Array").New(len(o.Include))
		for i, e := range o.Include {
			arr.SetIndex(i, e)
		}
		obj.Set("include", arr)
	}
	return obj
}

// R2HTTPMetadata
type R2HTTPMetadata struct {
	ContentType        string    `js:"contentType"`
	ContentLanguage    string    `js:"contentLanguage"`
	ContentDisposition string    `js:"contentDisposition"`
	ContentEncoding    string    `js:"contentEncoding"`
	CacheControl       string    `js:"cacheControl"`
	CacheExpiry        time.Time `js:"cacheExpiry"`
}

func r2HTTPMetadataFromJS(v js.Value) (R2HTTPMetadata, error) {
	var out R2HTTPMetadata
	{
		if s := v.Get("contentType"); !s.IsUndefined() && !s.IsNull() {
			out.ContentType = s.String()
		}
	}
	{
		if s := v.Get("contentLanguage"); !s.IsUndefined() && !s.IsNull() {
			out.ContentLanguage = s.String()
		}
	}
	{
		if s := v.Get("contentDisposition"); !s.IsUndefined() && !s.IsNull() {
			out.ContentDisposition = s.String()
		}
	}
	{
		if s := v.Get("contentEncoding"); !s.IsUndefined() && !s.IsNull() {
			out.ContentEncoding = s.String()
		}
	}
	{
		if s := v.Get("cacheControl"); !s.IsUndefined() && !s.IsNull() {
			out.CacheControl = s.String()
		}
	}
	{
		if s := v.Get("cacheExpiry"); !s.IsUndefined() && !s.IsNull() {
			out.CacheExpiry = jsrt.DateToTime(s)
		}
	}
	return out, nil
}

func (o R2HTTPMetadata) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ContentType != "" {
		obj.Set("contentType", o.ContentType)
	}
	if o.ContentLanguage != "" {
		obj.Set("contentLanguage", o.ContentLanguage)
	}
	if o.ContentDisposition != "" {
		obj.Set("contentDisposition", o.ContentDisposition)
	}
	if o.ContentEncoding != "" {
		obj.Set("contentEncoding", o.ContentEncoding)
	}
	if o.CacheControl != "" {
		obj.Set("cacheControl", o.CacheControl)
	}
	if !o.CacheExpiry.IsZero() {
		obj.Set("cacheExpiry", jsrt.TimeToDate(o.CacheExpiry))
	}
	return obj
}

// R2Range
type R2Range struct {
	Offset float64 `js:"offset"`
	Length float64 `js:"length"`
	Suffix float64 `js:"suffix"`
}

func r2RangeFromJS(v js.Value) (R2Range, error) {
	var out R2Range
	{
		if s := v.Get("offset"); !s.IsUndefined() && !s.IsNull() {
			out.Offset = s.Float()
		}
	}
	{
		if s := v.Get("length"); !s.IsUndefined() && !s.IsNull() {
			out.Length = s.Float()
		}
	}
	{
		if s := v.Get("suffix"); !s.IsUndefined() && !s.IsNull() {
			out.Suffix = s.Float()
		}
	}
	return out, nil
}

func (o R2Range) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Offset != 0 {
		obj.Set("offset", o.Offset)
	}
	if o.Length != 0 {
		obj.Set("length", o.Length)
	}
	if o.Suffix != 0 {
		obj.Set("suffix", o.Suffix)
	}
	return obj
}

// R2Conditional
type R2Conditional struct {
	EtagMatches        string    `js:"etagMatches"`
	EtagDoesNotMatch   string    `js:"etagDoesNotMatch"`
	UploadedBefore     time.Time `js:"uploadedBefore"`
	UploadedAfter      time.Time `js:"uploadedAfter"`
	SecondsGranularity bool      `js:"secondsGranularity"`
}

func r2ConditionalFromJS(v js.Value) (R2Conditional, error) {
	var out R2Conditional
	{
		if s := v.Get("etagMatches"); !s.IsUndefined() && !s.IsNull() {
			out.EtagMatches = s.String()
		}
	}
	{
		if s := v.Get("etagDoesNotMatch"); !s.IsUndefined() && !s.IsNull() {
			out.EtagDoesNotMatch = s.String()
		}
	}
	{
		if s := v.Get("uploadedBefore"); !s.IsUndefined() && !s.IsNull() {
			out.UploadedBefore = jsrt.DateToTime(s)
		}
	}
	{
		if s := v.Get("uploadedAfter"); !s.IsUndefined() && !s.IsNull() {
			out.UploadedAfter = jsrt.DateToTime(s)
		}
	}
	{
		if s := v.Get("secondsGranularity"); !s.IsUndefined() && !s.IsNull() {
			out.SecondsGranularity = s.Bool()
		}
	}
	return out, nil
}

func (o R2Conditional) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.EtagMatches != "" {
		obj.Set("etagMatches", o.EtagMatches)
	}
	if o.EtagDoesNotMatch != "" {
		obj.Set("etagDoesNotMatch", o.EtagDoesNotMatch)
	}
	if !o.UploadedBefore.IsZero() {
		obj.Set("uploadedBefore", jsrt.TimeToDate(o.UploadedBefore))
	}
	if !o.UploadedAfter.IsZero() {
		obj.Set("uploadedAfter", jsrt.TimeToDate(o.UploadedAfter))
	}
	if o.SecondsGranularity {
		obj.Set("secondsGranularity", o.SecondsGranularity)
	}
	return obj
}

// R2Checksums
type R2Checksums struct{ v js.Value }

// R2ChecksumsFromJS wraps a JS R2Checksums value.
func R2ChecksumsFromJS(v js.Value) *R2Checksums { return &R2Checksums{v: v} }

// JSValue returns the underlying JS value.
func (x *R2Checksums) JSValue() js.Value { return x.v }

// MD5
func (x *R2Checksums) MD5() []byte {
	var ret []byte
	if s := x.v.Get("md5"); !s.IsUndefined() && !s.IsNull() {
		ret = jsrt.BytesFromJS(s)
	}
	return ret
}

// Sha1
func (x *R2Checksums) Sha1() []byte {
	var ret []byte
	if s := x.v.Get("sha1"); !s.IsUndefined() && !s.IsNull() {
		ret = jsrt.BytesFromJS(s)
	}
	return ret
}

// Sha256
func (x *R2Checksums) Sha256() []byte {
	var ret []byte
	if s := x.v.Get("sha256"); !s.IsUndefined() && !s.IsNull() {
		ret = jsrt.BytesFromJS(s)
	}
	return ret
}

// Sha384
func (x *R2Checksums) Sha384() []byte {
	var ret []byte
	if s := x.v.Get("sha384"); !s.IsUndefined() && !s.IsNull() {
		ret = jsrt.BytesFromJS(s)
	}
	return ret
}

// Sha512
func (x *R2Checksums) Sha512() []byte {
	var ret []byte
	if s := x.v.Get("sha512"); !s.IsUndefined() && !s.IsNull() {
		ret = jsrt.BytesFromJS(s)
	}
	return ret
}

// ToJSON
func (x *R2Checksums) ToJSON() (R2StringChecksums, error) {
	r, err := jsrt.Call(x.v, "toJSON")
	if err != nil {
		return R2StringChecksums{}, err
	}
	var ret R2StringChecksums
	if tmp, err := r2StringChecksumsFromJS(r); err != nil {
		return R2StringChecksums{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// R2StringChecksums
type R2StringChecksums struct {
	MD5    string `js:"md5"`
	Sha1   string `js:"sha1"`
	Sha256 string `js:"sha256"`
	Sha384 string `js:"sha384"`
	Sha512 string `js:"sha512"`
}

func r2StringChecksumsFromJS(v js.Value) (R2StringChecksums, error) {
	var out R2StringChecksums
	{
		if s := v.Get("md5"); !s.IsUndefined() && !s.IsNull() {
			out.MD5 = s.String()
		}
	}
	{
		if s := v.Get("sha1"); !s.IsUndefined() && !s.IsNull() {
			out.Sha1 = s.String()
		}
	}
	{
		if s := v.Get("sha256"); !s.IsUndefined() && !s.IsNull() {
			out.Sha256 = s.String()
		}
	}
	{
		if s := v.Get("sha384"); !s.IsUndefined() && !s.IsNull() {
			out.Sha384 = s.String()
		}
	}
	{
		if s := v.Get("sha512"); !s.IsUndefined() && !s.IsNull() {
			out.Sha512 = s.String()
		}
	}
	return out, nil
}

func (o R2StringChecksums) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.MD5 != "" {
		obj.Set("md5", o.MD5)
	}
	if o.Sha1 != "" {
		obj.Set("sha1", o.Sha1)
	}
	if o.Sha256 != "" {
		obj.Set("sha256", o.Sha256)
	}
	if o.Sha384 != "" {
		obj.Set("sha384", o.Sha384)
	}
	if o.Sha512 != "" {
		obj.Set("sha512", o.Sha512)
	}
	return obj
}

// R2MultipartOptions
type R2MultipartOptions struct {
	HTTPMetadata   *R2HTTPMetadata   `js:"httpMetadata"`
	CustomMetadata map[string]string `js:"customMetadata"`
	StorageClass   string            `js:"storageClass"`
	SsecKey        string            `js:"ssecKey"`
}

func r2MultipartOptionsFromJS(v js.Value) (R2MultipartOptions, error) {
	var out R2MultipartOptions
	{
		if !jsrt.IsNil(v.Get("httpMetadata")) {
			var val R2HTTPMetadata
			if tmp, err := r2HTTPMetadataFromJS(v.Get("httpMetadata")); err != nil {
				return R2MultipartOptions{}, err
			} else {
				val = tmp
			}
			out.HTTPMetadata = &val
		}
	}
	{
		if s := v.Get("customMetadata"); !s.IsUndefined() && !s.IsNull() {
			out.CustomMetadata = make(map[string]string)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				var vv string
				vv = s.Get(k).String()
				out.CustomMetadata[k] = vv
			}
		}
	}
	{
		if s := v.Get("storageClass"); !s.IsUndefined() && !s.IsNull() {
			out.StorageClass = s.String()
		}
	}
	{
		if s := v.Get("ssecKey"); !s.IsUndefined() && !s.IsNull() {
			out.SsecKey = s.String()
		}
	}
	return out, nil
}

func (o R2MultipartOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.HTTPMetadata != nil {
		obj.Set("httpMetadata", (*o.HTTPMetadata).toJS())
	}
	if len(o.CustomMetadata) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.CustomMetadata {
			m.Set(k, v)
		}
		obj.Set("customMetadata", m)
	}
	if o.StorageClass != "" {
		obj.Set("storageClass", o.StorageClass)
	}
	if o.SsecKey != "" {
		obj.Set("ssecKey", o.SsecKey)
	}
	return obj
}

// R2MultipartUpload
type R2MultipartUpload struct{ v js.Value }

// R2MultipartUploadFromJS wraps a JS R2MultipartUpload value.
func R2MultipartUploadFromJS(v js.Value) *R2MultipartUpload { return &R2MultipartUpload{v: v} }

// JSValue returns the underlying JS value.
func (x *R2MultipartUpload) JSValue() js.Value { return x.v }

// Key
func (x *R2MultipartUpload) Key() string {
	var ret string
	ret = x.v.Get("key").String()
	return ret
}

// UploadID
func (x *R2MultipartUpload) UploadID() string {
	var ret string
	ret = x.v.Get("uploadId").String()
	return ret
}

// UploadPart
func (x *R2MultipartUpload) UploadPart(partNumber float64, value js.Value, options R2UploadPartOptions) (R2UploadedPart, error) {
	p, err := jsrt.Call(x.v, "uploadPart", partNumber, value, options.toJS())
	if err != nil {
		return R2UploadedPart{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return R2UploadedPart{}, err
	}
	var ret R2UploadedPart
	if tmp, err := r2UploadedPartFromJS(r); err != nil {
		return R2UploadedPart{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Abort
func (x *R2MultipartUpload) Abort() error {
	p, err := jsrt.Call(x.v, "abort")
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// Complete
func (x *R2MultipartUpload) Complete(uploadedParts []R2UploadedPart) (*R2Object, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(uploadedParts))
		for i, e := range uploadedParts {
			arr.SetIndex(i, e.toJS())
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "complete", arg0)
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *R2Object
	ret = R2ObjectFromJS(r)
	return ret, nil
}

// R2UploadedPart
type R2UploadedPart struct {
	PartNumber int    `js:"partNumber"`
	Etag       string `js:"etag"`
}

func r2UploadedPartFromJS(v js.Value) (R2UploadedPart, error) {
	var out R2UploadedPart
	{
		out.PartNumber = v.Get("partNumber").Int()
	}
	{
		out.Etag = v.Get("etag").String()
	}
	return out, nil
}

func (o R2UploadedPart) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.PartNumber != 0 {
		obj.Set("partNumber", o.PartNumber)
	}
	if o.Etag != "" {
		obj.Set("etag", o.Etag)
	}
	return obj
}

// R2UploadPartOptions
type R2UploadPartOptions struct {
	SsecKey string `js:"ssecKey"`
}

func r2UploadPartOptionsFromJS(v js.Value) (R2UploadPartOptions, error) {
	var out R2UploadPartOptions
	{
		if s := v.Get("ssecKey"); !s.IsUndefined() && !s.IsNull() {
			out.SsecKey = s.String()
		}
	}
	return out, nil
}

func (o R2UploadPartOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.SsecKey != "" {
		obj.Set("ssecKey", o.SsecKey)
	}
	return obj
}
