// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package versions provides the "version_metadata" binding, exposing
// metadata about the Worker Version using it.
//
// WorkerVersionMetadata is a TypeScript object-literal alias (not an
// interface), so it is generated as a data type: New resolves the binding
// and decodes it directly, since there is no underlying JS handle object to
// wrap.
package versions

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// WorkerVersionMetadata The interface for "version_metadata" binding
// providing metadata about the Worker Version using this binding.
type WorkerVersionMetadata struct {
	// The ID of the Worker Version using this binding
	ID string `js:"id"`
	// The tag of the Worker Version using this binding
	Tag string `js:"tag"`
	// The timestamp of when the Worker Version was uploaded
	Timestamp string `js:"timestamp"`
}

func workerVersionMetadataFromJS(v js.Value) (WorkerVersionMetadata, error) {
	var out WorkerVersionMetadata
	{
		out.ID = v.Get("id").String()
	}
	{
		out.Tag = v.Get("tag").String()
	}
	{
		out.Timestamp = v.Get("timestamp").String()
	}
	return out, nil
}

func (o WorkerVersionMetadata) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if o.Tag != "" {
		obj.Set("tag", o.Tag)
	}
	if o.Timestamp != "" {
		obj.Set("timestamp", o.Timestamp)
	}
	return obj
}

// NewWorkerVersionMetadata resolves the binding named bindingName from env.
func NewWorkerVersionMetadata(bindingName string) (WorkerVersionMetadata, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return WorkerVersionMetadata{}, err
	}
	return workerVersionMetadataFromJS(v)
}
