// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package queues provides the Queue producer binding
// (https://developers.cloudflare.com/queues/). The consumer side (Message,
// MessageBatch, the consumer handler registration) is hand-written under
// cloudflare/queues and isn't part of this generated package.
package queues

import (
	"syscall/js"
	"time"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Queue
type Queue struct{ v js.Value }

// QueueFromJS wraps a JS Queue value.
func QueueFromJS(v js.Value) *Queue { return &Queue{v: v} }

// JSValue returns the underlying JS value.
func (x *Queue) JSValue() js.Value { return x.v }

// NewQueue resolves the binding named bindingName from env.
func NewQueue(bindingName string) (*Queue, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &Queue{v: v}, nil
}

// Metrics
func (x *Queue) Metrics() (QueueMetrics, error) {
	p, err := jsrt.Call(x.v, "metrics")
	if err != nil {
		return QueueMetrics{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return QueueMetrics{}, err
	}
	var ret QueueMetrics
	if tmp, err := queueMetricsFromJS(r); err != nil {
		return QueueMetrics{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Send
func (x *Queue) Send(message js.Value, options QueueSendOptions) (QueueSendResponse, error) {
	p, err := jsrt.Call(x.v, "send", message, options.toJS())
	if err != nil {
		return QueueSendResponse{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return QueueSendResponse{}, err
	}
	var ret QueueSendResponse
	if tmp, err := queueSendResponseFromJS(r); err != nil {
		return QueueSendResponse{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// SendBatch
func (x *Queue) SendBatch(messages []MessageSendRequest, options QueueSendBatchOptions) (QueueSendBatchResponse, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(messages))
		for i, e := range messages {
			arr.SetIndex(i, e.toJS())
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "sendBatch", arg0, options.toJS())
	if err != nil {
		return QueueSendBatchResponse{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return QueueSendBatchResponse{}, err
	}
	var ret QueueSendBatchResponse
	if tmp, err := queueSendBatchResponseFromJS(r); err != nil {
		return QueueSendBatchResponse{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// MessageSendRequest
type MessageSendRequest struct {
	Body         js.Value         `js:"body"`
	ContentType  QueueContentType `js:"contentType"`
	DelaySeconds int              `js:"delaySeconds"`
}

func messageSendRequestFromJS(v js.Value) (MessageSendRequest, error) {
	var out MessageSendRequest
	{
		out.Body = v.Get("body")
	}
	{
		if s := v.Get("contentType"); !s.IsUndefined() && !s.IsNull() {
			out.ContentType = QueueContentType(s.String())
		}
	}
	{
		if s := v.Get("delaySeconds"); !s.IsUndefined() && !s.IsNull() {
			out.DelaySeconds = s.Int()
		}
	}
	return out, nil
}

func (o MessageSendRequest) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.Body) {
		obj.Set("body", o.Body)
	}
	if o.ContentType != "" {
		obj.Set("contentType", string(o.ContentType))
	}
	if o.DelaySeconds != 0 {
		obj.Set("delaySeconds", o.DelaySeconds)
	}
	return obj
}

// QueueSendOptions
type QueueSendOptions struct {
	ContentType  QueueContentType `js:"contentType"`
	DelaySeconds int              `js:"delaySeconds"`
}

func queueSendOptionsFromJS(v js.Value) (QueueSendOptions, error) {
	var out QueueSendOptions
	{
		if s := v.Get("contentType"); !s.IsUndefined() && !s.IsNull() {
			out.ContentType = QueueContentType(s.String())
		}
	}
	{
		if s := v.Get("delaySeconds"); !s.IsUndefined() && !s.IsNull() {
			out.DelaySeconds = s.Int()
		}
	}
	return out, nil
}

func (o QueueSendOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ContentType != "" {
		obj.Set("contentType", string(o.ContentType))
	}
	if o.DelaySeconds != 0 {
		obj.Set("delaySeconds", o.DelaySeconds)
	}
	return obj
}

// QueueSendBatchOptions
type QueueSendBatchOptions struct {
	DelaySeconds int `js:"delaySeconds"`
}

func queueSendBatchOptionsFromJS(v js.Value) (QueueSendBatchOptions, error) {
	var out QueueSendBatchOptions
	{
		if s := v.Get("delaySeconds"); !s.IsUndefined() && !s.IsNull() {
			out.DelaySeconds = s.Int()
		}
	}
	return out, nil
}

func (o QueueSendBatchOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.DelaySeconds != 0 {
		obj.Set("delaySeconds", o.DelaySeconds)
	}
	return obj
}

// QueueContentType
type QueueContentType string

const (
	QueueContentTypeText  QueueContentType = "text"
	QueueContentTypeBytes QueueContentType = "bytes"
	QueueContentTypeJSON  QueueContentType = "json"
	QueueContentTypeV8    QueueContentType = "v8"
)

// QueueSendResponse
type QueueSendResponse struct {
	Metadata QueueSendMetadata `js:"metadata"`
}

func queueSendResponseFromJS(v js.Value) (QueueSendResponse, error) {
	var out QueueSendResponse
	{
		if tmp, err := queueSendMetadataFromJS(v.Get("metadata")); err != nil {
			return QueueSendResponse{}, err
		} else {
			out.Metadata = tmp
		}
	}
	return out, nil
}

func (o QueueSendResponse) toJS() js.Value {
	obj := jsrt.NewObject()
	if true {
		obj.Set("metadata", o.Metadata.toJS())
	}
	return obj
}

// QueueSendBatchResponse
type QueueSendBatchResponse struct {
	Metadata QueueSendBatchMetadata `js:"metadata"`
}

func queueSendBatchResponseFromJS(v js.Value) (QueueSendBatchResponse, error) {
	var out QueueSendBatchResponse
	{
		if tmp, err := queueSendBatchMetadataFromJS(v.Get("metadata")); err != nil {
			return QueueSendBatchResponse{}, err
		} else {
			out.Metadata = tmp
		}
	}
	return out, nil
}

func (o QueueSendBatchResponse) toJS() js.Value {
	obj := jsrt.NewObject()
	if true {
		obj.Set("metadata", o.Metadata.toJS())
	}
	return obj
}

// QueueSendMetadata
type QueueSendMetadata struct {
	Metrics QueueSendMetrics `js:"metrics"`
}

func queueSendMetadataFromJS(v js.Value) (QueueSendMetadata, error) {
	var out QueueSendMetadata
	{
		if tmp, err := queueSendMetricsFromJS(v.Get("metrics")); err != nil {
			return QueueSendMetadata{}, err
		} else {
			out.Metrics = tmp
		}
	}
	return out, nil
}

func (o QueueSendMetadata) toJS() js.Value {
	obj := jsrt.NewObject()
	if true {
		obj.Set("metrics", o.Metrics.toJS())
	}
	return obj
}

// QueueSendBatchMetadata
type QueueSendBatchMetadata struct {
	Metrics QueueSendBatchMetrics `js:"metrics"`
}

func queueSendBatchMetadataFromJS(v js.Value) (QueueSendBatchMetadata, error) {
	var out QueueSendBatchMetadata
	{
		if tmp, err := queueSendBatchMetricsFromJS(v.Get("metrics")); err != nil {
			return QueueSendBatchMetadata{}, err
		} else {
			out.Metrics = tmp
		}
	}
	return out, nil
}

func (o QueueSendBatchMetadata) toJS() js.Value {
	obj := jsrt.NewObject()
	if true {
		obj.Set("metrics", o.Metrics.toJS())
	}
	return obj
}

// QueueSendMetrics
type QueueSendMetrics struct {
	BacklogCount           float64   `js:"backlogCount"`
	BacklogBytes           float64   `js:"backlogBytes"`
	OldestMessageTimestamp time.Time `js:"oldestMessageTimestamp"`
}

func queueSendMetricsFromJS(v js.Value) (QueueSendMetrics, error) {
	var out QueueSendMetrics
	{
		out.BacklogCount = v.Get("backlogCount").Float()
	}
	{
		out.BacklogBytes = v.Get("backlogBytes").Float()
	}
	{
		if s := v.Get("oldestMessageTimestamp"); !s.IsUndefined() && !s.IsNull() {
			out.OldestMessageTimestamp = jsrt.DateToTime(s)
		}
	}
	return out, nil
}

func (o QueueSendMetrics) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.BacklogCount != 0 {
		obj.Set("backlogCount", o.BacklogCount)
	}
	if o.BacklogBytes != 0 {
		obj.Set("backlogBytes", o.BacklogBytes)
	}
	if !o.OldestMessageTimestamp.IsZero() {
		obj.Set("oldestMessageTimestamp", jsrt.TimeToDate(o.OldestMessageTimestamp))
	}
	return obj
}

// QueueSendBatchMetrics
type QueueSendBatchMetrics struct {
	BacklogCount           float64   `js:"backlogCount"`
	BacklogBytes           float64   `js:"backlogBytes"`
	OldestMessageTimestamp time.Time `js:"oldestMessageTimestamp"`
}

func queueSendBatchMetricsFromJS(v js.Value) (QueueSendBatchMetrics, error) {
	var out QueueSendBatchMetrics
	{
		out.BacklogCount = v.Get("backlogCount").Float()
	}
	{
		out.BacklogBytes = v.Get("backlogBytes").Float()
	}
	{
		if s := v.Get("oldestMessageTimestamp"); !s.IsUndefined() && !s.IsNull() {
			out.OldestMessageTimestamp = jsrt.DateToTime(s)
		}
	}
	return out, nil
}

func (o QueueSendBatchMetrics) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.BacklogCount != 0 {
		obj.Set("backlogCount", o.BacklogCount)
	}
	if o.BacklogBytes != 0 {
		obj.Set("backlogBytes", o.BacklogBytes)
	}
	if !o.OldestMessageTimestamp.IsZero() {
		obj.Set("oldestMessageTimestamp", jsrt.TimeToDate(o.OldestMessageTimestamp))
	}
	return obj
}

// QueueMetrics
type QueueMetrics struct {
	BacklogCount           float64   `js:"backlogCount"`
	BacklogBytes           float64   `js:"backlogBytes"`
	OldestMessageTimestamp time.Time `js:"oldestMessageTimestamp"`
}

func queueMetricsFromJS(v js.Value) (QueueMetrics, error) {
	var out QueueMetrics
	{
		out.BacklogCount = v.Get("backlogCount").Float()
	}
	{
		out.BacklogBytes = v.Get("backlogBytes").Float()
	}
	{
		if s := v.Get("oldestMessageTimestamp"); !s.IsUndefined() && !s.IsNull() {
			out.OldestMessageTimestamp = jsrt.DateToTime(s)
		}
	}
	return out, nil
}

func (o QueueMetrics) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.BacklogCount != 0 {
		obj.Set("backlogCount", o.BacklogCount)
	}
	if o.BacklogBytes != 0 {
		obj.Set("backlogBytes", o.BacklogBytes)
	}
	if !o.OldestMessageTimestamp.IsZero() {
		obj.Set("oldestMessageTimestamp", jsrt.TimeToDate(o.OldestMessageTimestamp))
	}
	return obj
}
