// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package hyperdrive provides the Hyperdrive binding
// (https://developers.cloudflare.com/hyperdrive/).
//
// TODO: Hyperdrive.connect returns a Socket synchronously; bridging it to
// cloudflare/sockets' net.Conn wrapper is handwritten and not implemented
// in this phase. Call JSValue().Call("connect") directly in the meantime
// if you need it before the handwritten bridge lands.
package hyperdrive

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Hyperdrive
type Hyperdrive struct{ v js.Value }

// HyperdriveFromJS wraps a JS Hyperdrive value.
func HyperdriveFromJS(v js.Value) *Hyperdrive { return &Hyperdrive{v: v} }

// JSValue returns the underlying JS value.
func (x *Hyperdrive) JSValue() js.Value { return x.v }

// NewHyperdrive resolves the binding named bindingName from env.
func NewHyperdrive(bindingName string) (*Hyperdrive, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &Hyperdrive{v: v}, nil
}

// ConnectionString A valid DB connection string that can be passed straight into the typical
// client library/driver/ORM. This will typically be the easiest way to use
// Hyperdrive.
func (x *Hyperdrive) ConnectionString() string {
	var ret string
	ret = x.v.Get("connectionString").String()
	return ret
}

// Host
func (x *Hyperdrive) Host() string {
	var ret string
	ret = x.v.Get("host").String()
	return ret
}

// IP
func (x *Hyperdrive) IP() string {
	var ret string
	ret = x.v.Get("ip").String()
	return ret
}

// Port
func (x *Hyperdrive) Port() float64 {
	var ret float64
	ret = x.v.Get("port").Float()
	return ret
}

// User
func (x *Hyperdrive) User() string {
	var ret string
	ret = x.v.Get("user").String()
	return ret
}

// Password
func (x *Hyperdrive) Password() string {
	var ret string
	ret = x.v.Get("password").String()
	return ret
}

// Database
func (x *Hyperdrive) Database() string {
	var ret string
	ret = x.v.Get("database").String()
	return ret
}
