// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package cache provides the Cache API binding
// (https://developers.cloudflare.com/workers/runtime-apis/cache/).
//
// request/response are left as js.Value, a raw escape hatch: the L2 cache
// package (and anyone using this package directly) builds these from
// *http.Request/*http.Response via the same conversions jshttp already
// uses elsewhere. Caches() (in the hand-written cache.go in this package)
// is the entry point, wrapping the global caches CacheStorage.
package cache

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Cache The Cache API allows fine grained control of reading and writing from the Cloudflare global network cache.
//
// [Cloudflare Docs Reference](https://developers.cloudflare.com/workers/runtime-apis/cache/)
type Cache struct{ v js.Value }

// CacheFromJS wraps a JS Cache value.
func CacheFromJS(v js.Value) *Cache { return &Cache{v: v} }

// JSValue returns the underlying JS value.
func (x *Cache) JSValue() js.Value { return x.v }

// Delete
func (x *Cache) Delete(request js.Value, options CacheQueryOptions) (bool, error) {
	p, err := jsrt.Call(x.v, "delete", request, options.toJS())
	if err != nil {
		return false, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return false, err
	}
	var ret bool
	ret = r.Bool()
	return ret, nil
}

// Match
func (x *Cache) Match(request js.Value, options CacheQueryOptions) (js.Value, error) {
	p, err := jsrt.Call(x.v, "match", request, options.toJS())
	if err != nil {
		return js.Undefined(), err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return js.Undefined(), err
	}
	var ret js.Value
	ret = r
	return ret, nil
}

// Put
func (x *Cache) Put(request js.Value, response js.Value) error {
	p, err := jsrt.Call(x.v, "put", request, response)
	if err != nil {
		return err
	}
	_, err = jsrt.Await(p)
	return err
}

// CacheStorage The Cache API allows fine grained control of reading and writing from the Cloudflare global network cache.
//
// [Cloudflare Docs Reference](https://developers.cloudflare.com/workers/runtime-apis/cache/)
type CacheStorage struct{ v js.Value }

// CacheStorageFromJS wraps a JS CacheStorage value.
func CacheStorageFromJS(v js.Value) *CacheStorage { return &CacheStorage{v: v} }

// JSValue returns the underlying JS value.
func (x *CacheStorage) JSValue() js.Value { return x.v }

// Open The **`open()`** method of the CacheStorage interface returns a Promise that resolves to the Cache object matching the cacheName.
//
// [MDN Reference](https://developer.mozilla.org/docs/Web/API/CacheStorage/open)
func (x *CacheStorage) Open(cacheName string) (*Cache, error) {
	p, err := jsrt.Call(x.v, "open", cacheName)
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret *Cache
	ret = CacheFromJS(r)
	return ret, nil
}

// Default
func (x *CacheStorage) Default() *Cache {
	var ret *Cache
	ret = CacheFromJS(x.v.Get("default"))
	return ret
}

// CacheQueryOptions
type CacheQueryOptions struct {
	IgnoreMethod bool `js:"ignoreMethod"`
}

func cacheQueryOptionsFromJS(v js.Value) (CacheQueryOptions, error) {
	var out CacheQueryOptions
	{
		if s := v.Get("ignoreMethod"); !s.IsUndefined() && !s.IsNull() {
			out.IgnoreMethod = s.Bool()
		}
	}
	return out, nil
}

func (o CacheQueryOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.IgnoreMethod {
		obj.Set("ignoreMethod", o.IgnoreMethod)
	}
	return obj
}
