// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package ratelimit provides the Rate Limiting binding
// (https://developers.cloudflare.com/workers/runtime-apis/bindings/rate-limit/).
//
// This is the minimal-configuration reference package for cfgen: it uses no
// renames, type overrides, or overloads.
package ratelimit

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// RateLimit
type RateLimit struct{ v js.Value }

// RateLimitFromJS wraps a JS RateLimit value.
func RateLimitFromJS(v js.Value) *RateLimit { return &RateLimit{v: v} }

// JSValue returns the underlying JS value.
func (x *RateLimit) JSValue() js.Value { return x.v }

// NewRateLimit resolves the binding named bindingName from env.
func NewRateLimit(bindingName string) (*RateLimit, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &RateLimit{v: v}, nil
}

// Limit Rate limit a request based on the provided options.
// @see https://developers.cloudflare.com/workers/runtime-apis/bindings/rate-limit/
// @returns A promise that resolves with the outcome of the rate limit.
func (x *RateLimit) Limit(options RateLimitOptions) (RateLimitOutcome, error) {
	p, err := jsrt.Call(x.v, "limit", options.toJS())
	if err != nil {
		return RateLimitOutcome{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return RateLimitOutcome{}, err
	}
	var ret RateLimitOutcome
	if tmp, err := rateLimitOutcomeFromJS(r); err != nil {
		return RateLimitOutcome{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// RateLimitOptions
type RateLimitOptions struct {
	Key string `js:"key"`
}

func rateLimitOptionsFromJS(v js.Value) (RateLimitOptions, error) {
	var out RateLimitOptions
	{
		out.Key = v.Get("key").String()
	}
	return out, nil
}

func (o RateLimitOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Key != "" {
		obj.Set("key", o.Key)
	}
	return obj
}

// RateLimitOutcome
type RateLimitOutcome struct {
	Success bool `js:"success"`
}

func rateLimitOutcomeFromJS(v js.Value) (RateLimitOutcome, error) {
	var out RateLimitOutcome
	{
		out.Success = v.Get("success").Bool()
	}
	return out, nil
}

func (o RateLimitOutcome) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Success {
		obj.Set("success", o.Success)
	}
	return obj
}
