// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package vectorize provides the current-generation Vectorize binding
// (https://developers.cloudflare.com/vectorize/). Mutations on this
// binding are async, returning a mutation id rather than the mutated
// vectors directly.
//
// The .d.ts source also declares an older, synchronous-mutation
// VectorizeIndex interface; this package intentionally wraps only the
// current-generation Vectorize binding, per the migration guidance at
// https://developers.cloudflare.com/vectorize/reference/transition-vectorize-legacy/.
package vectorize

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// Vectorize A Vectorize Vector Search Index for querying vectors/embeddings.
//
// Mutations in this version are async, returning a mutation id.
type Vectorize struct{ v js.Value }

// VectorizeFromJS wraps a JS Vectorize value.
func VectorizeFromJS(v js.Value) *Vectorize { return &Vectorize{v: v} }

// JSValue returns the underlying JS value.
func (x *Vectorize) JSValue() js.Value { return x.v }

// NewVectorize resolves the binding named bindingName from env.
func NewVectorize(bindingName string) (*Vectorize, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &Vectorize{v: v}, nil
}

// Describe Get information about the currently bound index.
// @returns A promise that resolves with information about the current index.
func (x *Vectorize) Describe() (VectorizeIndexInfo, error) {
	p, err := jsrt.Call(x.v, "describe")
	if err != nil {
		return VectorizeIndexInfo{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return VectorizeIndexInfo{}, err
	}
	var ret VectorizeIndexInfo
	if tmp, err := vectorizeIndexInfoFromJS(r); err != nil {
		return VectorizeIndexInfo{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Query Use the provided vector to perform a similarity search across the index.
// @param vector Input vector that will be used to drive the similarity search.
// @param options Configuration options to massage the returned data.
// @returns A promise that resolves with matched and scored vectors.
func (x *Vectorize) Query(vector []float32, options VectorizeQueryOptions) (VectorizeMatches, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(vector))
		for i, e := range vector {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "query", arg0, options.toJS())
	if err != nil {
		return VectorizeMatches{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return VectorizeMatches{}, err
	}
	var ret VectorizeMatches
	if tmp, err := vectorizeMatchesFromJS(r); err != nil {
		return VectorizeMatches{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// QueryByID Use the provided vector-id to perform a similarity search across the index.
// @param vectorId Id for a vector in the index against which the index should be queried.
// @param options Configuration options to massage the returned data.
// @returns A promise that resolves with matched and scored vectors.
func (x *Vectorize) QueryByID(vectorId string, options VectorizeQueryOptions) (VectorizeMatches, error) {
	p, err := jsrt.Call(x.v, "queryById", vectorId, options.toJS())
	if err != nil {
		return VectorizeMatches{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return VectorizeMatches{}, err
	}
	var ret VectorizeMatches
	if tmp, err := vectorizeMatchesFromJS(r); err != nil {
		return VectorizeMatches{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Insert Insert a list of vectors into the index dataset. If a provided id exists, an error will be thrown.
// @param vectors List of vectors that will be inserted.
// @returns A promise that resolves with a unique identifier of a mutation containing the insert changeset.
func (x *Vectorize) Insert(vectors []VectorizeVector) (VectorizeAsyncMutation, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(vectors))
		for i, e := range vectors {
			arr.SetIndex(i, e.toJS())
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "insert", arg0)
	if err != nil {
		return VectorizeAsyncMutation{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return VectorizeAsyncMutation{}, err
	}
	var ret VectorizeAsyncMutation
	if tmp, err := vectorizeAsyncMutationFromJS(r); err != nil {
		return VectorizeAsyncMutation{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// Upsert Upsert a list of vectors into the index dataset. If a provided id exists, it will be replaced with the new values.
// @param vectors List of vectors that will be upserted.
// @returns A promise that resolves with a unique identifier of a mutation containing the upsert changeset.
func (x *Vectorize) Upsert(vectors []VectorizeVector) (VectorizeAsyncMutation, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(vectors))
		for i, e := range vectors {
			arr.SetIndex(i, e.toJS())
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "upsert", arg0)
	if err != nil {
		return VectorizeAsyncMutation{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return VectorizeAsyncMutation{}, err
	}
	var ret VectorizeAsyncMutation
	if tmp, err := vectorizeAsyncMutationFromJS(r); err != nil {
		return VectorizeAsyncMutation{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// DeleteByIds Delete a list of vectors with a matching id.
// @param ids List of vector ids that should be deleted.
// @returns A promise that resolves with a unique identifier of a mutation containing the delete changeset.
func (x *Vectorize) DeleteByIds(ids []string) (VectorizeAsyncMutation, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(ids))
		for i, e := range ids {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "deleteByIds", arg0)
	if err != nil {
		return VectorizeAsyncMutation{}, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return VectorizeAsyncMutation{}, err
	}
	var ret VectorizeAsyncMutation
	if tmp, err := vectorizeAsyncMutationFromJS(r); err != nil {
		return VectorizeAsyncMutation{}, err
	} else {
		ret = tmp
	}
	return ret, nil
}

// GetByIds Get a list of vectors with a matching id.
// @param ids List of vector ids that should be returned.
// @returns A promise that resolves with the raw unscored vectors matching the id set.
func (x *Vectorize) GetByIds(ids []string) ([]VectorizeVector, error) {
	var arg0 js.Value
	{
		arr := js.Global().Get("Array").New(len(ids))
		for i, e := range ids {
			arr.SetIndex(i, e)
		}
		arg0 = arr
	}
	p, err := jsrt.Call(x.v, "getByIds", arg0)
	if err != nil {
		return nil, err
	}
	r, err := jsrt.Await(p)
	if err != nil {
		return nil, err
	}
	var ret []VectorizeVector
	ret = make([]VectorizeVector, r.Length())
	for i := range ret {
		if tmp, err := vectorizeVectorFromJS(r.Index(i)); err != nil {
			return nil, err
		} else {
			ret[i] = tmp
		}
	}
	return ret, nil
}

// VectorizeVector Represents a single vector value set along with its associated metadata.
type VectorizeVector struct {
	// The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents.
	ID string `js:"id"`
	// The vector values
	Values []float32 `js:"values"`
	// The namespace this vector belongs to.
	Namespace string `js:"namespace"`
	// Metadata associated with the vector. Includes the values of other fields and potentially additional details.
	Metadata map[string]any `js:"metadata"`
}

func vectorizeVectorFromJS(v js.Value) (VectorizeVector, error) {
	var out VectorizeVector
	{
		out.ID = v.Get("id").String()
	}
	{
		out.Values = make([]float32, v.Get("values").Length())
		for i := range out.Values {
			out.Values[i] = float32(v.Get("values").Index(i).Float())
		}
	}
	{
		if s := v.Get("namespace"); !s.IsUndefined() && !s.IsNull() {
			out.Namespace = s.String()
		}
	}
	{
		if s := v.Get("metadata"); !s.IsUndefined() && !s.IsNull() {
			out.Metadata = make(map[string]any)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				out.Metadata[k] = s.Get(k)
			}
		}
	}
	return out, nil
}

func (o VectorizeVector) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ID != "" {
		obj.Set("id", o.ID)
	}
	if len(o.Values) > 0 {
		arr := js.Global().Get("Array").New(len(o.Values))
		for i, e := range o.Values {
			arr.SetIndex(i, e)
		}
		obj.Set("values", arr)
	}
	if o.Namespace != "" {
		obj.Set("namespace", o.Namespace)
	}
	if len(o.Metadata) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.Metadata {
			m.Set(k, v)
		}
		obj.Set("metadata", m)
	}
	return obj
}

// VectorizeQueryOptions
type VectorizeQueryOptions struct {
	TopK           float64        `js:"topK"`
	Namespace      string         `js:"namespace"`
	ReturnValues   bool           `js:"returnValues"`
	ReturnMetadata js.Value       `js:"returnMetadata"`
	Filter         map[string]any `js:"filter"`
}

func vectorizeQueryOptionsFromJS(v js.Value) (VectorizeQueryOptions, error) {
	var out VectorizeQueryOptions
	{
		if s := v.Get("topK"); !s.IsUndefined() && !s.IsNull() {
			out.TopK = s.Float()
		}
	}
	{
		if s := v.Get("namespace"); !s.IsUndefined() && !s.IsNull() {
			out.Namespace = s.String()
		}
	}
	{
		if s := v.Get("returnValues"); !s.IsUndefined() && !s.IsNull() {
			out.ReturnValues = s.Bool()
		}
	}
	{
		if s := v.Get("returnMetadata"); !s.IsUndefined() && !s.IsNull() {
			out.ReturnMetadata = s
		}
	}
	{
		if s := v.Get("filter"); !s.IsUndefined() && !s.IsNull() {
			out.Filter = make(map[string]any)
			keys := js.Global().Get("Object").Call("keys", s)
			for i := 0; i < keys.Length(); i++ {
				k := keys.Index(i).String()
				out.Filter[k] = s.Get(k)
			}
		}
	}
	return out, nil
}

func (o VectorizeQueryOptions) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.TopK != 0 {
		obj.Set("topK", o.TopK)
	}
	if o.Namespace != "" {
		obj.Set("namespace", o.Namespace)
	}
	if o.ReturnValues {
		obj.Set("returnValues", o.ReturnValues)
	}
	if !jsrt.IsNil(o.ReturnMetadata) {
		obj.Set("returnMetadata", o.ReturnMetadata)
	}
	if len(o.Filter) > 0 {
		m := jsrt.NewObject()
		for k, v := range o.Filter {
			m.Set(k, v)
		}
		obj.Set("filter", m)
	}
	return obj
}

// VectorizeMatches A set of matching {@link VectorizeMatch} for a particular query.
type VectorizeMatches struct {
	Matches []js.Value `js:"matches"`
	Count   float64    `js:"count"`
}

func vectorizeMatchesFromJS(v js.Value) (VectorizeMatches, error) {
	var out VectorizeMatches
	{
		out.Matches = make([]js.Value, v.Get("matches").Length())
		for i := range out.Matches {
			out.Matches[i] = v.Get("matches").Index(i)
		}
	}
	{
		out.Count = v.Get("count").Float()
	}
	return out, nil
}

func (o VectorizeMatches) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Matches) > 0 {
		arr := js.Global().Get("Array").New(len(o.Matches))
		for i, e := range o.Matches {
			arr.SetIndex(i, e)
		}
		obj.Set("matches", arr)
	}
	if o.Count != 0 {
		obj.Set("count", o.Count)
	}
	return obj
}

// VectorizeMatch Represents a matched vector for a query along with its score and (if specified) the matching vector information.
type VectorizeMatch = js.Value

// VectorizeVectorMutation Results of an operation that performed a mutation on a set of vectors.
// Here, `ids` is a list of vectors that were successfully processed.
//
// This type is exclusively for the Vectorize **beta** and will be deprecated once Vectorize RC is released.
// See {@link VectorizeAsyncMutation} for its post-beta equivalent.
type VectorizeVectorMutation struct {
	Ids   []string `js:"ids"`
	Count float64  `js:"count"`
}

func vectorizeVectorMutationFromJS(v js.Value) (VectorizeVectorMutation, error) {
	var out VectorizeVectorMutation
	{
		out.Ids = make([]string, v.Get("ids").Length())
		for i := range out.Ids {
			out.Ids[i] = v.Get("ids").Index(i).String()
		}
	}
	{
		out.Count = v.Get("count").Float()
	}
	return out, nil
}

func (o VectorizeVectorMutation) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Ids) > 0 {
		arr := js.Global().Get("Array").New(len(o.Ids))
		for i, e := range o.Ids {
			arr.SetIndex(i, e)
		}
		obj.Set("ids", arr)
	}
	if o.Count != 0 {
		obj.Set("count", o.Count)
	}
	return obj
}

// VectorizeIndexInfo Metadata about an existing index.
type VectorizeIndexInfo struct {
	// The number of records containing vectors within the index.
	VectorCount float64 `js:"vectorCount"`
	// Number of dimensions the index has been configured for.
	Dimensions float64 `js:"dimensions"`
	// ISO 8601 datetime of the last processed mutation on in the index. All changes before this mutation will be reflected in the index state.
	ProcessedUpToDatetime float64 `js:"processedUpToDatetime"`
	// UUIDv4 of the last mutation processed by the index. All changes before this mutation will be reflected in the index state.
	ProcessedUpToMutation float64 `js:"processedUpToMutation"`
}

func vectorizeIndexInfoFromJS(v js.Value) (VectorizeIndexInfo, error) {
	var out VectorizeIndexInfo
	{
		out.VectorCount = v.Get("vectorCount").Float()
	}
	{
		out.Dimensions = v.Get("dimensions").Float()
	}
	{
		out.ProcessedUpToDatetime = v.Get("processedUpToDatetime").Float()
	}
	{
		out.ProcessedUpToMutation = v.Get("processedUpToMutation").Float()
	}
	return out, nil
}

func (o VectorizeIndexInfo) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.VectorCount != 0 {
		obj.Set("vectorCount", o.VectorCount)
	}
	if o.Dimensions != 0 {
		obj.Set("dimensions", o.Dimensions)
	}
	if o.ProcessedUpToDatetime != 0 {
		obj.Set("processedUpToDatetime", o.ProcessedUpToDatetime)
	}
	if o.ProcessedUpToMutation != 0 {
		obj.Set("processedUpToMutation", o.ProcessedUpToMutation)
	}
	return obj
}

// VectorizeAsyncMutation Result type indicating a mutation on the Vectorize Index.
// Actual mutations are processed async where the `mutationId` is the unique identifier for the operation.
type VectorizeAsyncMutation struct {
	// The unique identifier for the async mutation operation containing the changeset.
	MutationID string `js:"mutationId"`
}

func vectorizeAsyncMutationFromJS(v js.Value) (VectorizeAsyncMutation, error) {
	var out VectorizeAsyncMutation
	{
		out.MutationID = v.Get("mutationId").String()
	}
	return out, nil
}

func (o VectorizeAsyncMutation) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.MutationID != "" {
		obj.Set("mutationId", o.MutationID)
	}
	return obj
}
