// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package cf provides IncomingRequestCfProperties, the metadata
// Cloudflare's edge attaches to a request (available on the underlying
// Fetch API Request as `request.cf`). These are pure data types: there is
// no JS handle object involved, only fromJS decoding, so this package has
// no bindings.
//
// In the .d.ts source, IncomingRequestCfProperties is assembled as a
// TypeScript intersection of several smaller interfaces (which themselves
// use `extends`). cfgen flattens that composition into one Go struct, so
// every field is reachable directly off IncomingRequestCfProperties. Each
// constituent interface is also generated standalone below, for callers
// that only have one piece (e.g. a bot management report) in hand.
//
// FromRequest and FromJS, which decode a *http.Request / raw js.Value into
// an IncomingRequestCfProperties, are hand-written in cf.go.
package cf

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// IncomingRequestCFProperties Request metadata provided by Cloudflare's edge.
type IncomingRequestCFProperties struct {
	// [ASN](https://www.iana.org/assignments/as-numbers/as-numbers.xhtml) of the incoming request.
	//
	// @example 395747
	ASN float64 `js:"asn"`
	// The organization which owns the ASN of the incoming request.
	//
	// @example "Google Cloud"
	AsOrganization string `js:"asOrganization"`
	// The original value of the `Accept-Encoding` header if Cloudflare modified it.
	//
	// @example "gzip, deflate, br"
	ClientAcceptEncoding string `js:"clientAcceptEncoding"`
	// The number of milliseconds it took for the request to reach your worker.
	//
	// @example 22
	ClientTcpRtt float64 `js:"clientTcpRtt"`
	// The three-letter [IATA](https://en.wikipedia.org/wiki/IATA_airport_code)
	// airport code of the data center that the request hit.
	//
	// @example "DFW"
	Colo string `js:"colo"`
	// Represents the upstream's response to a
	// [TCP `keepalive` message](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html)
	// from cloudflare.
	//
	// For workers with no upstream, this will always be `1`.
	//
	// @example 3
	EdgeRequestKeepAliveStatus int `js:"edgeRequestKeepAliveStatus"`
	// The HTTP Protocol the request used.
	//
	// @example "HTTP/2"
	HTTPProtocol string `js:"httpProtocol"`
	// The browser-requested prioritization information in the request object.
	//
	// If no information was set, defaults to the empty string `""`
	//
	// @example "weight=192;exclusive=0;group=3;group-weight=127"
	// @default ""
	RequestPriority string `js:"requestPriority"`
	// The TLS version of the connection to Cloudflare.
	// In requests served over plaintext (without TLS), this property is the empty string `""`.
	//
	// @example "TLSv1.3"
	TLSVersion string `js:"tlsVersion"`
	// The cipher for the connection to Cloudflare.
	// In requests served over plaintext (without TLS), this property is the empty string `""`.
	//
	// @example "AEAD-AES128-GCM-SHA256"
	TLSCipher string `js:"tlsCipher"`
	// Metadata containing the [`HELLO`](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2) and [`FINISHED`](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9) messages from this request's TLS handshake.
	//
	// If the incoming request was served over plaintext (without TLS) this field is undefined.
	TLSExportedAuthenticator *IncomingRequestCFPropertiesExportedAuthenticatorMetadata `js:"tlsExportedAuthenticator"`
	// Results of Cloudflare's Bot Management analysis
	BotManagement js.Value `js:"botManagement"`
	// Duplicate of `botManagement.score`.
	//
	// @deprecated
	ClientTrustScore float64 `js:"clientTrustScore"`
	// Custom metadata set per-host in [Cloudflare for SaaS](https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/).
	//
	// This field is only present if you have Cloudflare for SaaS enabled on your account
	// and you have followed the [required steps to enable it]((https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/domain-support/custom-metadata/)).
	HostMetadata js.Value `js:"hostMetadata"`
	// The [ISO 3166-1 Alpha 2](https://www.iso.org/iso-3166-country-codes.html) country code the request originated from.
	//
	// If your worker is [configured to accept TOR connections](https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing), this may also be `"T1"`, indicating a request that originated over TOR.
	//
	// If Cloudflare is unable to determine where the request originated this property is omitted.
	//
	// The country code `"T1"` is used for requests originating on TOR.
	//
	// @example "GB"
	Country js.Value `js:"country"`
	// If present, this property indicates that the request originated in the EU
	//
	// @example "1"
	IsEUCountry string `js:"isEUCountry"`
	// A two-letter code indicating the continent the request originated from.
	//
	// @example "AN"
	Continent js.Value `js:"continent"`
	// The city the request originated from
	//
	// @example "Austin"
	City string `js:"city"`
	// Postal code of the incoming request
	//
	// @example "78701"
	PostalCode string `js:"postalCode"`
	// Latitude of the incoming request
	//
	// @example "30.27130"
	Latitude string `js:"latitude"`
	// Longitude of the incoming request
	//
	// @example "-97.74260"
	Longitude string `js:"longitude"`
	// Timezone of the incoming request
	//
	// @example "America/Chicago"
	Timezone string `js:"timezone"`
	// If known, the ISO 3166-2 name for the first level region associated with
	// the IP address of the incoming request
	//
	// @example "Texas"
	Region string `js:"region"`
	// If known, the ISO 3166-2 code for the first-level region associated with
	// the IP address of the incoming request
	//
	// @example "TX"
	RegionCode string `js:"regionCode"`
	// Metro code (DMA) of the incoming request
	//
	// @example "635"
	MetroCode string `js:"metroCode"`
	// Information about the client certificate presented to Cloudflare.
	//
	// This is populated when the incoming request is served over TLS using
	// either Cloudflare Access or API Shield (mTLS)
	// and the presented SSL certificate has a valid
	// [Certificate Serial Number](https://ldapwiki.com/wiki/Certificate%20Serial%20Number)
	// (i.e., not `null` or `""`).
	//
	// Otherwise, a set of placeholder values are used.
	//
	// The property `certPresented` will be set to `"1"` when
	// the object is populated (i.e. the above conditions were met).
	TLSClientAuth js.Value `js:"tlsClientAuth"`
}

func incomingRequestCFPropertiesFromJS(v js.Value) (IncomingRequestCFProperties, error) {
	var out IncomingRequestCFProperties
	{
		if s := v.Get("asn"); !s.IsUndefined() && !s.IsNull() {
			out.ASN = s.Float()
		}
	}
	{
		if s := v.Get("asOrganization"); !s.IsUndefined() && !s.IsNull() {
			out.AsOrganization = s.String()
		}
	}
	{
		if s := v.Get("clientAcceptEncoding"); !s.IsUndefined() && !s.IsNull() {
			out.ClientAcceptEncoding = s.String()
		}
	}
	{
		if s := v.Get("clientTcpRtt"); !s.IsUndefined() && !s.IsNull() {
			out.ClientTcpRtt = s.Float()
		}
	}
	{
		out.Colo = v.Get("colo").String()
	}
	{
		out.EdgeRequestKeepAliveStatus = v.Get("edgeRequestKeepAliveStatus").Int()
	}
	{
		out.HTTPProtocol = v.Get("httpProtocol").String()
	}
	{
		out.RequestPriority = v.Get("requestPriority").String()
	}
	{
		out.TLSVersion = v.Get("tlsVersion").String()
	}
	{
		out.TLSCipher = v.Get("tlsCipher").String()
	}
	{
		if !jsrt.IsNil(v.Get("tlsExportedAuthenticator")) {
			var val IncomingRequestCFPropertiesExportedAuthenticatorMetadata
			if tmp, err := incomingRequestCFPropertiesExportedAuthenticatorMetadataFromJS(v.Get("tlsExportedAuthenticator")); err != nil {
				return IncomingRequestCFProperties{}, err
			} else {
				val = tmp
			}
			out.TLSExportedAuthenticator = &val
		}
	}
	{
		out.BotManagement = v.Get("botManagement")
	}
	{
		out.ClientTrustScore = v.Get("clientTrustScore").Float()
	}
	{
		if s := v.Get("hostMetadata"); !s.IsUndefined() && !s.IsNull() {
			out.HostMetadata = s
		}
	}
	{
		if s := v.Get("country"); !s.IsUndefined() && !s.IsNull() {
			out.Country = s
		}
	}
	{
		if s := v.Get("isEUCountry"); !s.IsUndefined() && !s.IsNull() {
			out.IsEUCountry = s.String()
		}
	}
	{
		if s := v.Get("continent"); !s.IsUndefined() && !s.IsNull() {
			out.Continent = s
		}
	}
	{
		if s := v.Get("city"); !s.IsUndefined() && !s.IsNull() {
			out.City = s.String()
		}
	}
	{
		if s := v.Get("postalCode"); !s.IsUndefined() && !s.IsNull() {
			out.PostalCode = s.String()
		}
	}
	{
		if s := v.Get("latitude"); !s.IsUndefined() && !s.IsNull() {
			out.Latitude = s.String()
		}
	}
	{
		if s := v.Get("longitude"); !s.IsUndefined() && !s.IsNull() {
			out.Longitude = s.String()
		}
	}
	{
		if s := v.Get("timezone"); !s.IsUndefined() && !s.IsNull() {
			out.Timezone = s.String()
		}
	}
	{
		if s := v.Get("region"); !s.IsUndefined() && !s.IsNull() {
			out.Region = s.String()
		}
	}
	{
		if s := v.Get("regionCode"); !s.IsUndefined() && !s.IsNull() {
			out.RegionCode = s.String()
		}
	}
	{
		if s := v.Get("metroCode"); !s.IsUndefined() && !s.IsNull() {
			out.MetroCode = s.String()
		}
	}
	{
		out.TLSClientAuth = v.Get("tlsClientAuth")
	}
	return out, nil
}

func (o IncomingRequestCFProperties) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ASN != 0 {
		obj.Set("asn", o.ASN)
	}
	if o.AsOrganization != "" {
		obj.Set("asOrganization", o.AsOrganization)
	}
	if o.ClientAcceptEncoding != "" {
		obj.Set("clientAcceptEncoding", o.ClientAcceptEncoding)
	}
	if o.ClientTcpRtt != 0 {
		obj.Set("clientTcpRtt", o.ClientTcpRtt)
	}
	if o.Colo != "" {
		obj.Set("colo", o.Colo)
	}
	if o.EdgeRequestKeepAliveStatus != 0 {
		obj.Set("edgeRequestKeepAliveStatus", o.EdgeRequestKeepAliveStatus)
	}
	if o.HTTPProtocol != "" {
		obj.Set("httpProtocol", o.HTTPProtocol)
	}
	if o.RequestPriority != "" {
		obj.Set("requestPriority", o.RequestPriority)
	}
	if o.TLSVersion != "" {
		obj.Set("tlsVersion", o.TLSVersion)
	}
	if o.TLSCipher != "" {
		obj.Set("tlsCipher", o.TLSCipher)
	}
	if o.TLSExportedAuthenticator != nil {
		obj.Set("tlsExportedAuthenticator", (*o.TLSExportedAuthenticator).toJS())
	}
	if !jsrt.IsNil(o.BotManagement) {
		obj.Set("botManagement", o.BotManagement)
	}
	if o.ClientTrustScore != 0 {
		obj.Set("clientTrustScore", o.ClientTrustScore)
	}
	if !jsrt.IsNil(o.HostMetadata) {
		obj.Set("hostMetadata", o.HostMetadata)
	}
	if !jsrt.IsNil(o.Country) {
		obj.Set("country", o.Country)
	}
	if o.IsEUCountry != "" {
		obj.Set("isEUCountry", o.IsEUCountry)
	}
	if !jsrt.IsNil(o.Continent) {
		obj.Set("continent", o.Continent)
	}
	if o.City != "" {
		obj.Set("city", o.City)
	}
	if o.PostalCode != "" {
		obj.Set("postalCode", o.PostalCode)
	}
	if o.Latitude != "" {
		obj.Set("latitude", o.Latitude)
	}
	if o.Longitude != "" {
		obj.Set("longitude", o.Longitude)
	}
	if o.Timezone != "" {
		obj.Set("timezone", o.Timezone)
	}
	if o.Region != "" {
		obj.Set("region", o.Region)
	}
	if o.RegionCode != "" {
		obj.Set("regionCode", o.RegionCode)
	}
	if o.MetroCode != "" {
		obj.Set("metroCode", o.MetroCode)
	}
	if !jsrt.IsNil(o.TLSClientAuth) {
		obj.Set("tlsClientAuth", o.TLSClientAuth)
	}
	return obj
}

// IncomingRequestCFPropertiesBase
type IncomingRequestCFPropertiesBase struct {
	// [ASN](https://www.iana.org/assignments/as-numbers/as-numbers.xhtml) of the incoming request.
	//
	// @example 395747
	ASN float64 `js:"asn"`
	// The organization which owns the ASN of the incoming request.
	//
	// @example "Google Cloud"
	AsOrganization string `js:"asOrganization"`
	// The original value of the `Accept-Encoding` header if Cloudflare modified it.
	//
	// @example "gzip, deflate, br"
	ClientAcceptEncoding string `js:"clientAcceptEncoding"`
	// The number of milliseconds it took for the request to reach your worker.
	//
	// @example 22
	ClientTcpRtt float64 `js:"clientTcpRtt"`
	// The three-letter [IATA](https://en.wikipedia.org/wiki/IATA_airport_code)
	// airport code of the data center that the request hit.
	//
	// @example "DFW"
	Colo string `js:"colo"`
	// Represents the upstream's response to a
	// [TCP `keepalive` message](https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html)
	// from cloudflare.
	//
	// For workers with no upstream, this will always be `1`.
	//
	// @example 3
	EdgeRequestKeepAliveStatus int `js:"edgeRequestKeepAliveStatus"`
	// The HTTP Protocol the request used.
	//
	// @example "HTTP/2"
	HTTPProtocol string `js:"httpProtocol"`
	// The browser-requested prioritization information in the request object.
	//
	// If no information was set, defaults to the empty string `""`
	//
	// @example "weight=192;exclusive=0;group=3;group-weight=127"
	// @default ""
	RequestPriority string `js:"requestPriority"`
	// The TLS version of the connection to Cloudflare.
	// In requests served over plaintext (without TLS), this property is the empty string `""`.
	//
	// @example "TLSv1.3"
	TLSVersion string `js:"tlsVersion"`
	// The cipher for the connection to Cloudflare.
	// In requests served over plaintext (without TLS), this property is the empty string `""`.
	//
	// @example "AEAD-AES128-GCM-SHA256"
	TLSCipher string `js:"tlsCipher"`
	// Metadata containing the [`HELLO`](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2) and [`FINISHED`](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9) messages from this request's TLS handshake.
	//
	// If the incoming request was served over plaintext (without TLS) this field is undefined.
	TLSExportedAuthenticator *IncomingRequestCFPropertiesExportedAuthenticatorMetadata `js:"tlsExportedAuthenticator"`
}

func incomingRequestCFPropertiesBaseFromJS(v js.Value) (IncomingRequestCFPropertiesBase, error) {
	var out IncomingRequestCFPropertiesBase
	{
		if s := v.Get("asn"); !s.IsUndefined() && !s.IsNull() {
			out.ASN = s.Float()
		}
	}
	{
		if s := v.Get("asOrganization"); !s.IsUndefined() && !s.IsNull() {
			out.AsOrganization = s.String()
		}
	}
	{
		if s := v.Get("clientAcceptEncoding"); !s.IsUndefined() && !s.IsNull() {
			out.ClientAcceptEncoding = s.String()
		}
	}
	{
		if s := v.Get("clientTcpRtt"); !s.IsUndefined() && !s.IsNull() {
			out.ClientTcpRtt = s.Float()
		}
	}
	{
		out.Colo = v.Get("colo").String()
	}
	{
		out.EdgeRequestKeepAliveStatus = v.Get("edgeRequestKeepAliveStatus").Int()
	}
	{
		out.HTTPProtocol = v.Get("httpProtocol").String()
	}
	{
		out.RequestPriority = v.Get("requestPriority").String()
	}
	{
		out.TLSVersion = v.Get("tlsVersion").String()
	}
	{
		out.TLSCipher = v.Get("tlsCipher").String()
	}
	{
		if !jsrt.IsNil(v.Get("tlsExportedAuthenticator")) {
			var val IncomingRequestCFPropertiesExportedAuthenticatorMetadata
			if tmp, err := incomingRequestCFPropertiesExportedAuthenticatorMetadataFromJS(v.Get("tlsExportedAuthenticator")); err != nil {
				return IncomingRequestCFPropertiesBase{}, err
			} else {
				val = tmp
			}
			out.TLSExportedAuthenticator = &val
		}
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesBase) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ASN != 0 {
		obj.Set("asn", o.ASN)
	}
	if o.AsOrganization != "" {
		obj.Set("asOrganization", o.AsOrganization)
	}
	if o.ClientAcceptEncoding != "" {
		obj.Set("clientAcceptEncoding", o.ClientAcceptEncoding)
	}
	if o.ClientTcpRtt != 0 {
		obj.Set("clientTcpRtt", o.ClientTcpRtt)
	}
	if o.Colo != "" {
		obj.Set("colo", o.Colo)
	}
	if o.EdgeRequestKeepAliveStatus != 0 {
		obj.Set("edgeRequestKeepAliveStatus", o.EdgeRequestKeepAliveStatus)
	}
	if o.HTTPProtocol != "" {
		obj.Set("httpProtocol", o.HTTPProtocol)
	}
	if o.RequestPriority != "" {
		obj.Set("requestPriority", o.RequestPriority)
	}
	if o.TLSVersion != "" {
		obj.Set("tlsVersion", o.TLSVersion)
	}
	if o.TLSCipher != "" {
		obj.Set("tlsCipher", o.TLSCipher)
	}
	if o.TLSExportedAuthenticator != nil {
		obj.Set("tlsExportedAuthenticator", (*o.TLSExportedAuthenticator).toJS())
	}
	return obj
}

// IncomingRequestCFPropertiesBotManagement
type IncomingRequestCFPropertiesBotManagement struct {
	// Results of Cloudflare's Bot Management analysis
	BotManagement IncomingRequestCFPropertiesBotManagementBase `js:"botManagement"`
	// Duplicate of `botManagement.score`.
	//
	// @deprecated
	ClientTrustScore float64 `js:"clientTrustScore"`
}

func incomingRequestCFPropertiesBotManagementFromJS(v js.Value) (IncomingRequestCFPropertiesBotManagement, error) {
	var out IncomingRequestCFPropertiesBotManagement
	{
		if tmp, err := incomingRequestCFPropertiesBotManagementBaseFromJS(v.Get("botManagement")); err != nil {
			return IncomingRequestCFPropertiesBotManagement{}, err
		} else {
			out.BotManagement = tmp
		}
	}
	{
		out.ClientTrustScore = v.Get("clientTrustScore").Float()
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesBotManagement) toJS() js.Value {
	obj := jsrt.NewObject()
	if true {
		obj.Set("botManagement", o.BotManagement.toJS())
	}
	if o.ClientTrustScore != 0 {
		obj.Set("clientTrustScore", o.ClientTrustScore)
	}
	return obj
}

// IncomingRequestCFPropertiesBotManagementBase
type IncomingRequestCFPropertiesBotManagementBase struct {
	// Cloudflare’s [level of certainty](https://developers.cloudflare.com/bots/concepts/bot-score/) that a request comes from a bot,
	// represented as an integer percentage between `1` (almost certainly a bot) and `99` (almost certainly human).
	//
	// @example 54
	Score float64 `js:"score"`
	// A boolean value that is true if the request comes from a good bot, like Google or Bing.
	// Most customers choose to allow this traffic. For more details, see [Traffic from known bots](https://developers.cloudflare.com/firewall/known-issues-and-faq/#how-does-firewall-rules-handle-traffic-from-known-bots).
	VerifiedBot bool `js:"verifiedBot"`
	// A boolean value that is true if the request originates from a
	// Cloudflare-verified proxy service.
	CorporateProxy bool `js:"corporateProxy"`
	// A boolean value that's true if the request matches [file extensions](https://developers.cloudflare.com/bots/reference/static-resources/) for many types of static resources.
	StaticResource bool `js:"staticResource"`
	// List of IDs that correlate to the Bot Management heuristic detections made on a request (you can have multiple heuristic detections on the same request).
	DetectionIds []float64 `js:"detectionIds"`
}

func incomingRequestCFPropertiesBotManagementBaseFromJS(v js.Value) (IncomingRequestCFPropertiesBotManagementBase, error) {
	var out IncomingRequestCFPropertiesBotManagementBase
	{
		out.Score = v.Get("score").Float()
	}
	{
		out.VerifiedBot = v.Get("verifiedBot").Bool()
	}
	{
		out.CorporateProxy = v.Get("corporateProxy").Bool()
	}
	{
		out.StaticResource = v.Get("staticResource").Bool()
	}
	{
		out.DetectionIds = make([]float64, v.Get("detectionIds").Length())
		for i := range out.DetectionIds {
			out.DetectionIds[i] = v.Get("detectionIds").Index(i).Float()
		}
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesBotManagementBase) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.Score != 0 {
		obj.Set("score", o.Score)
	}
	if o.VerifiedBot {
		obj.Set("verifiedBot", o.VerifiedBot)
	}
	if o.CorporateProxy {
		obj.Set("corporateProxy", o.CorporateProxy)
	}
	if o.StaticResource {
		obj.Set("staticResource", o.StaticResource)
	}
	if len(o.DetectionIds) > 0 {
		arr := js.Global().Get("Array").New(len(o.DetectionIds))
		for i, e := range o.DetectionIds {
			arr.SetIndex(i, e)
		}
		obj.Set("detectionIds", arr)
	}
	return obj
}

// IncomingRequestCFPropertiesBotManagementEnterprise
type IncomingRequestCFPropertiesBotManagementEnterprise struct {
	// Results of Cloudflare's Bot Management analysis
	BotManagement js.Value `js:"botManagement"`
	// Duplicate of `botManagement.score`.
	//
	// @deprecated
	ClientTrustScore float64 `js:"clientTrustScore"`
}

func incomingRequestCFPropertiesBotManagementEnterpriseFromJS(v js.Value) (IncomingRequestCFPropertiesBotManagementEnterprise, error) {
	var out IncomingRequestCFPropertiesBotManagementEnterprise
	{
		out.BotManagement = v.Get("botManagement")
	}
	{
		out.ClientTrustScore = v.Get("clientTrustScore").Float()
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesBotManagementEnterprise) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.BotManagement) {
		obj.Set("botManagement", o.BotManagement)
	}
	if o.ClientTrustScore != 0 {
		obj.Set("clientTrustScore", o.ClientTrustScore)
	}
	return obj
}

// IncomingRequestCFPropertiesTLSClientAuth Data about the incoming request's TLS certificate
type IncomingRequestCFPropertiesTLSClientAuth struct {
	// Always `"1"`, indicating that the certificate was presented
	CertPresented string `js:"certPresented"`
	// Result of certificate verification.
	//
	// @example "FAILED:self signed certificate"
	CertVerified js.Value `js:"certVerified"`
	// The presented certificate's revokation status.
	//
	// - A value of `"1"` indicates the certificate has been revoked
	// - A value of `"0"` indicates the certificate has not been revoked
	CertRevoked string `js:"certRevoked"`
	// The certificate issuer's [distinguished name](https://knowledge.digicert.com/generalinformation/INFO1745.html)
	//
	// @example "CN=cloudflareaccess.com, C=US, ST=Texas, L=Austin, O=Cloudflare"
	CertIssuerDN string `js:"certIssuerDN"`
	// The certificate subject's [distinguished name](https://knowledge.digicert.com/generalinformation/INFO1745.html)
	//
	// @example "CN=*.cloudflareaccess.com, C=US, ST=Texas, L=Austin, O=Cloudflare"
	CertSubjectDN string `js:"certSubjectDN"`
	// The certificate issuer's [distinguished name](https://knowledge.digicert.com/generalinformation/INFO1745.html) ([RFC 2253](https://www.rfc-editor.org/rfc/rfc2253.html) formatted)
	//
	// @example "CN=cloudflareaccess.com, C=US, ST=Texas, L=Austin, O=Cloudflare"
	CertIssuerDNRFC2253 string `js:"certIssuerDNRFC2253"`
	// The certificate subject's [distinguished name](https://knowledge.digicert.com/generalinformation/INFO1745.html) ([RFC 2253](https://www.rfc-editor.org/rfc/rfc2253.html) formatted)
	//
	// @example "CN=*.cloudflareaccess.com, C=US, ST=Texas, L=Austin, O=Cloudflare"
	CertSubjectDNRFC2253 string `js:"certSubjectDNRFC2253"`
	// The certificate issuer's distinguished name (legacy policies)
	CertIssuerDNLegacy string `js:"certIssuerDNLegacy"`
	// The certificate subject's distinguished name (legacy policies)
	CertSubjectDNLegacy string `js:"certSubjectDNLegacy"`
	// The certificate's serial number
	//
	// @example "00936EACBE07F201DF"
	CertSerial string `js:"certSerial"`
	// The certificate issuer's serial number
	//
	// @example "2489002934BDFEA34"
	CertIssuerSerial string `js:"certIssuerSerial"`
	// The certificate's Subject Key Identifier
	//
	// @example "BB:AF:7E:02:3D:FA:A6:F1:3C:84:8E:AD:EE:38:98:EC:D9:32:32:D4"
	CertSKI string `js:"certSKI"`
	// The certificate issuer's Subject Key Identifier
	//
	// @example "BB:AF:7E:02:3D:FA:A6:F1:3C:84:8E:AD:EE:38:98:EC:D9:32:32:D4"
	CertIssuerSKI string `js:"certIssuerSKI"`
	// The certificate's SHA-1 fingerprint
	//
	// @example "6b9109f323999e52259cda7373ff0b4d26bd232e"
	CertFingerprintSHA1 string `js:"certFingerprintSHA1"`
	// The certificate's SHA-256 fingerprint
	//
	// @example "acf77cf37b4156a2708e34c4eb755f9b5dbbe5ebb55adfec8f11493438d19e6ad3f157f81fa3b98278453d5652b0c1fd1d71e5695ae4d709803a4d3f39de9dea"
	CertFingerprintSHA256 string `js:"certFingerprintSHA256"`
	// The effective starting date of the certificate
	//
	// @example "Dec 22 19:39:00 2018 GMT"
	CertNotBefore string `js:"certNotBefore"`
	// The effective expiration date of the certificate
	//
	// @example "Dec 22 19:39:00 2018 GMT"
	CertNotAfter string `js:"certNotAfter"`
	// The client leaf certificate in [RFC 9440](https://www.rfc-editor.org/rfc/rfc9440)
	// format (`:base64-DER:`). Empty if no client certificate was presented or if
	// the leaf certificate exceeded 10 KB (see {@link certRFC9440TooLarge}).
	//
	// Suitable for forwarding to an origin via the `Client-Cert` HTTP header.
	CertRFC9440 string `js:"certRFC9440"`
	// `true` if the leaf certificate exceeded 10 KB and was omitted from
	// {@link certRFC9440}.
	CertRFC9440TooLarge bool `js:"certRFC9440TooLarge"`
	// The intermediate certificate chain in [RFC 9440](https://www.rfc-editor.org/rfc/rfc9440)
	// format as a comma-separated list. Empty if no intermediates were sent or
	// if the chain exceeded 16 KB (see {@link certChainRFC9440TooLarge}).
	//
	// Suitable for forwarding to an origin via the `Client-Cert-Chain` HTTP header.
	CertChainRFC9440 string `js:"certChainRFC9440"`
	// `true` if the intermediate chain exceeded 16 KB and was omitted from
	// {@link certChainRFC9440}.
	CertChainRFC9440TooLarge bool `js:"certChainRFC9440TooLarge"`
}

func incomingRequestCFPropertiesTLSClientAuthFromJS(v js.Value) (IncomingRequestCFPropertiesTLSClientAuth, error) {
	var out IncomingRequestCFPropertiesTLSClientAuth
	{
		out.CertPresented = v.Get("certPresented").String()
	}
	{
		out.CertVerified = v.Get("certVerified")
	}
	{
		out.CertRevoked = v.Get("certRevoked").String()
	}
	{
		out.CertIssuerDN = v.Get("certIssuerDN").String()
	}
	{
		out.CertSubjectDN = v.Get("certSubjectDN").String()
	}
	{
		out.CertIssuerDNRFC2253 = v.Get("certIssuerDNRFC2253").String()
	}
	{
		out.CertSubjectDNRFC2253 = v.Get("certSubjectDNRFC2253").String()
	}
	{
		out.CertIssuerDNLegacy = v.Get("certIssuerDNLegacy").String()
	}
	{
		out.CertSubjectDNLegacy = v.Get("certSubjectDNLegacy").String()
	}
	{
		out.CertSerial = v.Get("certSerial").String()
	}
	{
		out.CertIssuerSerial = v.Get("certIssuerSerial").String()
	}
	{
		out.CertSKI = v.Get("certSKI").String()
	}
	{
		out.CertIssuerSKI = v.Get("certIssuerSKI").String()
	}
	{
		out.CertFingerprintSHA1 = v.Get("certFingerprintSHA1").String()
	}
	{
		out.CertFingerprintSHA256 = v.Get("certFingerprintSHA256").String()
	}
	{
		out.CertNotBefore = v.Get("certNotBefore").String()
	}
	{
		out.CertNotAfter = v.Get("certNotAfter").String()
	}
	{
		out.CertRFC9440 = v.Get("certRFC9440").String()
	}
	{
		out.CertRFC9440TooLarge = v.Get("certRFC9440TooLarge").Bool()
	}
	{
		out.CertChainRFC9440 = v.Get("certChainRFC9440").String()
	}
	{
		out.CertChainRFC9440TooLarge = v.Get("certChainRFC9440TooLarge").Bool()
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesTLSClientAuth) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.CertPresented != "" {
		obj.Set("certPresented", o.CertPresented)
	}
	if !jsrt.IsNil(o.CertVerified) {
		obj.Set("certVerified", o.CertVerified)
	}
	if o.CertRevoked != "" {
		obj.Set("certRevoked", o.CertRevoked)
	}
	if o.CertIssuerDN != "" {
		obj.Set("certIssuerDN", o.CertIssuerDN)
	}
	if o.CertSubjectDN != "" {
		obj.Set("certSubjectDN", o.CertSubjectDN)
	}
	if o.CertIssuerDNRFC2253 != "" {
		obj.Set("certIssuerDNRFC2253", o.CertIssuerDNRFC2253)
	}
	if o.CertSubjectDNRFC2253 != "" {
		obj.Set("certSubjectDNRFC2253", o.CertSubjectDNRFC2253)
	}
	if o.CertIssuerDNLegacy != "" {
		obj.Set("certIssuerDNLegacy", o.CertIssuerDNLegacy)
	}
	if o.CertSubjectDNLegacy != "" {
		obj.Set("certSubjectDNLegacy", o.CertSubjectDNLegacy)
	}
	if o.CertSerial != "" {
		obj.Set("certSerial", o.CertSerial)
	}
	if o.CertIssuerSerial != "" {
		obj.Set("certIssuerSerial", o.CertIssuerSerial)
	}
	if o.CertSKI != "" {
		obj.Set("certSKI", o.CertSKI)
	}
	if o.CertIssuerSKI != "" {
		obj.Set("certIssuerSKI", o.CertIssuerSKI)
	}
	if o.CertFingerprintSHA1 != "" {
		obj.Set("certFingerprintSHA1", o.CertFingerprintSHA1)
	}
	if o.CertFingerprintSHA256 != "" {
		obj.Set("certFingerprintSHA256", o.CertFingerprintSHA256)
	}
	if o.CertNotBefore != "" {
		obj.Set("certNotBefore", o.CertNotBefore)
	}
	if o.CertNotAfter != "" {
		obj.Set("certNotAfter", o.CertNotAfter)
	}
	if o.CertRFC9440 != "" {
		obj.Set("certRFC9440", o.CertRFC9440)
	}
	if o.CertRFC9440TooLarge {
		obj.Set("certRFC9440TooLarge", o.CertRFC9440TooLarge)
	}
	if o.CertChainRFC9440 != "" {
		obj.Set("certChainRFC9440", o.CertChainRFC9440)
	}
	if o.CertChainRFC9440TooLarge {
		obj.Set("certChainRFC9440TooLarge", o.CertChainRFC9440TooLarge)
	}
	return obj
}

// IncomingRequestCFPropertiesTLSClientAuthPlaceholder Placeholder values for TLS Client Authorization
type IncomingRequestCFPropertiesTLSClientAuthPlaceholder struct {
	CertPresented            string `js:"certPresented"`
	CertVerified             string `js:"certVerified"`
	CertRevoked              string `js:"certRevoked"`
	CertIssuerDN             string `js:"certIssuerDN"`
	CertSubjectDN            string `js:"certSubjectDN"`
	CertIssuerDNRFC2253      string `js:"certIssuerDNRFC2253"`
	CertSubjectDNRFC2253     string `js:"certSubjectDNRFC2253"`
	CertIssuerDNLegacy       string `js:"certIssuerDNLegacy"`
	CertSubjectDNLegacy      string `js:"certSubjectDNLegacy"`
	CertSerial               string `js:"certSerial"`
	CertIssuerSerial         string `js:"certIssuerSerial"`
	CertSKI                  string `js:"certSKI"`
	CertIssuerSKI            string `js:"certIssuerSKI"`
	CertFingerprintSHA1      string `js:"certFingerprintSHA1"`
	CertFingerprintSHA256    string `js:"certFingerprintSHA256"`
	CertNotBefore            string `js:"certNotBefore"`
	CertNotAfter             string `js:"certNotAfter"`
	CertRFC9440              string `js:"certRFC9440"`
	CertRFC9440TooLarge      bool   `js:"certRFC9440TooLarge"`
	CertChainRFC9440         string `js:"certChainRFC9440"`
	CertChainRFC9440TooLarge bool   `js:"certChainRFC9440TooLarge"`
}

func incomingRequestCFPropertiesTLSClientAuthPlaceholderFromJS(v js.Value) (IncomingRequestCFPropertiesTLSClientAuthPlaceholder, error) {
	var out IncomingRequestCFPropertiesTLSClientAuthPlaceholder
	{
		out.CertPresented = v.Get("certPresented").String()
	}
	{
		out.CertVerified = v.Get("certVerified").String()
	}
	{
		out.CertRevoked = v.Get("certRevoked").String()
	}
	{
		out.CertIssuerDN = v.Get("certIssuerDN").String()
	}
	{
		out.CertSubjectDN = v.Get("certSubjectDN").String()
	}
	{
		out.CertIssuerDNRFC2253 = v.Get("certIssuerDNRFC2253").String()
	}
	{
		out.CertSubjectDNRFC2253 = v.Get("certSubjectDNRFC2253").String()
	}
	{
		out.CertIssuerDNLegacy = v.Get("certIssuerDNLegacy").String()
	}
	{
		out.CertSubjectDNLegacy = v.Get("certSubjectDNLegacy").String()
	}
	{
		out.CertSerial = v.Get("certSerial").String()
	}
	{
		out.CertIssuerSerial = v.Get("certIssuerSerial").String()
	}
	{
		out.CertSKI = v.Get("certSKI").String()
	}
	{
		out.CertIssuerSKI = v.Get("certIssuerSKI").String()
	}
	{
		out.CertFingerprintSHA1 = v.Get("certFingerprintSHA1").String()
	}
	{
		out.CertFingerprintSHA256 = v.Get("certFingerprintSHA256").String()
	}
	{
		out.CertNotBefore = v.Get("certNotBefore").String()
	}
	{
		out.CertNotAfter = v.Get("certNotAfter").String()
	}
	{
		out.CertRFC9440 = v.Get("certRFC9440").String()
	}
	{
		out.CertRFC9440TooLarge = v.Get("certRFC9440TooLarge").Bool()
	}
	{
		out.CertChainRFC9440 = v.Get("certChainRFC9440").String()
	}
	{
		out.CertChainRFC9440TooLarge = v.Get("certChainRFC9440TooLarge").Bool()
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesTLSClientAuthPlaceholder) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.CertPresented != "" {
		obj.Set("certPresented", o.CertPresented)
	}
	if o.CertVerified != "" {
		obj.Set("certVerified", o.CertVerified)
	}
	if o.CertRevoked != "" {
		obj.Set("certRevoked", o.CertRevoked)
	}
	if o.CertIssuerDN != "" {
		obj.Set("certIssuerDN", o.CertIssuerDN)
	}
	if o.CertSubjectDN != "" {
		obj.Set("certSubjectDN", o.CertSubjectDN)
	}
	if o.CertIssuerDNRFC2253 != "" {
		obj.Set("certIssuerDNRFC2253", o.CertIssuerDNRFC2253)
	}
	if o.CertSubjectDNRFC2253 != "" {
		obj.Set("certSubjectDNRFC2253", o.CertSubjectDNRFC2253)
	}
	if o.CertIssuerDNLegacy != "" {
		obj.Set("certIssuerDNLegacy", o.CertIssuerDNLegacy)
	}
	if o.CertSubjectDNLegacy != "" {
		obj.Set("certSubjectDNLegacy", o.CertSubjectDNLegacy)
	}
	if o.CertSerial != "" {
		obj.Set("certSerial", o.CertSerial)
	}
	if o.CertIssuerSerial != "" {
		obj.Set("certIssuerSerial", o.CertIssuerSerial)
	}
	if o.CertSKI != "" {
		obj.Set("certSKI", o.CertSKI)
	}
	if o.CertIssuerSKI != "" {
		obj.Set("certIssuerSKI", o.CertIssuerSKI)
	}
	if o.CertFingerprintSHA1 != "" {
		obj.Set("certFingerprintSHA1", o.CertFingerprintSHA1)
	}
	if o.CertFingerprintSHA256 != "" {
		obj.Set("certFingerprintSHA256", o.CertFingerprintSHA256)
	}
	if o.CertNotBefore != "" {
		obj.Set("certNotBefore", o.CertNotBefore)
	}
	if o.CertNotAfter != "" {
		obj.Set("certNotAfter", o.CertNotAfter)
	}
	if o.CertRFC9440 != "" {
		obj.Set("certRFC9440", o.CertRFC9440)
	}
	if o.CertRFC9440TooLarge {
		obj.Set("certRFC9440TooLarge", o.CertRFC9440TooLarge)
	}
	if o.CertChainRFC9440 != "" {
		obj.Set("certChainRFC9440", o.CertChainRFC9440)
	}
	if o.CertChainRFC9440TooLarge {
		obj.Set("certChainRFC9440TooLarge", o.CertChainRFC9440TooLarge)
	}
	return obj
}

// IncomingRequestCFPropertiesGeographicInformation Geographic data about the request's origin.
type IncomingRequestCFPropertiesGeographicInformation struct {
	// The [ISO 3166-1 Alpha 2](https://www.iso.org/iso-3166-country-codes.html) country code the request originated from.
	//
	// If your worker is [configured to accept TOR connections](https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing), this may also be `"T1"`, indicating a request that originated over TOR.
	//
	// If Cloudflare is unable to determine where the request originated this property is omitted.
	//
	// The country code `"T1"` is used for requests originating on TOR.
	//
	// @example "GB"
	Country js.Value `js:"country"`
	// If present, this property indicates that the request originated in the EU
	//
	// @example "1"
	IsEUCountry string `js:"isEUCountry"`
	// A two-letter code indicating the continent the request originated from.
	//
	// @example "AN"
	Continent js.Value `js:"continent"`
	// The city the request originated from
	//
	// @example "Austin"
	City string `js:"city"`
	// Postal code of the incoming request
	//
	// @example "78701"
	PostalCode string `js:"postalCode"`
	// Latitude of the incoming request
	//
	// @example "30.27130"
	Latitude string `js:"latitude"`
	// Longitude of the incoming request
	//
	// @example "-97.74260"
	Longitude string `js:"longitude"`
	// Timezone of the incoming request
	//
	// @example "America/Chicago"
	Timezone string `js:"timezone"`
	// If known, the ISO 3166-2 name for the first level region associated with
	// the IP address of the incoming request
	//
	// @example "Texas"
	Region string `js:"region"`
	// If known, the ISO 3166-2 code for the first-level region associated with
	// the IP address of the incoming request
	//
	// @example "TX"
	RegionCode string `js:"regionCode"`
	// Metro code (DMA) of the incoming request
	//
	// @example "635"
	MetroCode string `js:"metroCode"`
}

func incomingRequestCFPropertiesGeographicInformationFromJS(v js.Value) (IncomingRequestCFPropertiesGeographicInformation, error) {
	var out IncomingRequestCFPropertiesGeographicInformation
	{
		if s := v.Get("country"); !s.IsUndefined() && !s.IsNull() {
			out.Country = s
		}
	}
	{
		if s := v.Get("isEUCountry"); !s.IsUndefined() && !s.IsNull() {
			out.IsEUCountry = s.String()
		}
	}
	{
		if s := v.Get("continent"); !s.IsUndefined() && !s.IsNull() {
			out.Continent = s
		}
	}
	{
		if s := v.Get("city"); !s.IsUndefined() && !s.IsNull() {
			out.City = s.String()
		}
	}
	{
		if s := v.Get("postalCode"); !s.IsUndefined() && !s.IsNull() {
			out.PostalCode = s.String()
		}
	}
	{
		if s := v.Get("latitude"); !s.IsUndefined() && !s.IsNull() {
			out.Latitude = s.String()
		}
	}
	{
		if s := v.Get("longitude"); !s.IsUndefined() && !s.IsNull() {
			out.Longitude = s.String()
		}
	}
	{
		if s := v.Get("timezone"); !s.IsUndefined() && !s.IsNull() {
			out.Timezone = s.String()
		}
	}
	{
		if s := v.Get("region"); !s.IsUndefined() && !s.IsNull() {
			out.Region = s.String()
		}
	}
	{
		if s := v.Get("regionCode"); !s.IsUndefined() && !s.IsNull() {
			out.RegionCode = s.String()
		}
	}
	{
		if s := v.Get("metroCode"); !s.IsUndefined() && !s.IsNull() {
			out.MetroCode = s.String()
		}
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesGeographicInformation) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.Country) {
		obj.Set("country", o.Country)
	}
	if o.IsEUCountry != "" {
		obj.Set("isEUCountry", o.IsEUCountry)
	}
	if !jsrt.IsNil(o.Continent) {
		obj.Set("continent", o.Continent)
	}
	if o.City != "" {
		obj.Set("city", o.City)
	}
	if o.PostalCode != "" {
		obj.Set("postalCode", o.PostalCode)
	}
	if o.Latitude != "" {
		obj.Set("latitude", o.Latitude)
	}
	if o.Longitude != "" {
		obj.Set("longitude", o.Longitude)
	}
	if o.Timezone != "" {
		obj.Set("timezone", o.Timezone)
	}
	if o.Region != "" {
		obj.Set("region", o.Region)
	}
	if o.RegionCode != "" {
		obj.Set("regionCode", o.RegionCode)
	}
	if o.MetroCode != "" {
		obj.Set("metroCode", o.MetroCode)
	}
	return obj
}

// IncomingRequestCFPropertiesCloudflareForSaaSEnterprise
type IncomingRequestCFPropertiesCloudflareForSaaSEnterprise struct {
	// Custom metadata set per-host in [Cloudflare for SaaS](https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/).
	//
	// This field is only present if you have Cloudflare for SaaS enabled on your account
	// and you have followed the [required steps to enable it]((https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/domain-support/custom-metadata/)).
	HostMetadata js.Value `js:"hostMetadata"`
}

func incomingRequestCFPropertiesCloudflareForSaaSEnterpriseFromJS(v js.Value) (IncomingRequestCFPropertiesCloudflareForSaaSEnterprise, error) {
	var out IncomingRequestCFPropertiesCloudflareForSaaSEnterprise
	{
		if s := v.Get("hostMetadata"); !s.IsUndefined() && !s.IsNull() {
			out.HostMetadata = s
		}
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesCloudflareForSaaSEnterprise) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.HostMetadata) {
		obj.Set("hostMetadata", o.HostMetadata)
	}
	return obj
}

// IncomingRequestCFPropertiesCloudflareAccessOrAPIShield
type IncomingRequestCFPropertiesCloudflareAccessOrAPIShield struct {
	// Information about the client certificate presented to Cloudflare.
	//
	// This is populated when the incoming request is served over TLS using
	// either Cloudflare Access or API Shield (mTLS)
	// and the presented SSL certificate has a valid
	// [Certificate Serial Number](https://ldapwiki.com/wiki/Certificate%20Serial%20Number)
	// (i.e., not `null` or `""`).
	//
	// Otherwise, a set of placeholder values are used.
	//
	// The property `certPresented` will be set to `"1"` when
	// the object is populated (i.e. the above conditions were met).
	TLSClientAuth js.Value `js:"tlsClientAuth"`
}

func incomingRequestCFPropertiesCloudflareAccessOrAPIShieldFromJS(v js.Value) (IncomingRequestCFPropertiesCloudflareAccessOrAPIShield, error) {
	var out IncomingRequestCFPropertiesCloudflareAccessOrAPIShield
	{
		out.TLSClientAuth = v.Get("tlsClientAuth")
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesCloudflareAccessOrAPIShield) toJS() js.Value {
	obj := jsrt.NewObject()
	if !jsrt.IsNil(o.TLSClientAuth) {
		obj.Set("tlsClientAuth", o.TLSClientAuth)
	}
	return obj
}

// IncomingRequestCFPropertiesExportedAuthenticatorMetadata Metadata about the request's TLS handshake
type IncomingRequestCFPropertiesExportedAuthenticatorMetadata struct {
	// The client's [`HELLO` message](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2), encoded in hexadecimal
	//
	// @example "44372ba35fa1270921d318f34c12f155dc87b682cf36a790cfaa3ba8737a1b5d"
	ClientHandshake string `js:"clientHandshake"`
	// The server's [`HELLO` message](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2), encoded in hexadecimal
	//
	// @example "44372ba35fa1270921d318f34c12f155dc87b682cf36a790cfaa3ba8737a1b5d"
	ServerHandshake string `js:"serverHandshake"`
	// The client's [`FINISHED` message](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9), encoded in hexadecimal
	//
	// @example "084ee802fe1348f688220e2a6040a05b2199a761f33cf753abb1b006792d3f8b"
	ClientFinished string `js:"clientFinished"`
	// The server's [`FINISHED` message](https://www.rfc-editor.org/rfc/rfc5246#section-7.4.9), encoded in hexadecimal
	//
	// @example "084ee802fe1348f688220e2a6040a05b2199a761f33cf753abb1b006792d3f8b"
	ServerFinished string `js:"serverFinished"`
}

func incomingRequestCFPropertiesExportedAuthenticatorMetadataFromJS(v js.Value) (IncomingRequestCFPropertiesExportedAuthenticatorMetadata, error) {
	var out IncomingRequestCFPropertiesExportedAuthenticatorMetadata
	{
		out.ClientHandshake = v.Get("clientHandshake").String()
	}
	{
		out.ServerHandshake = v.Get("serverHandshake").String()
	}
	{
		out.ClientFinished = v.Get("clientFinished").String()
	}
	{
		out.ServerFinished = v.Get("serverFinished").String()
	}
	return out, nil
}

func (o IncomingRequestCFPropertiesExportedAuthenticatorMetadata) toJS() js.Value {
	obj := jsrt.NewObject()
	if o.ClientHandshake != "" {
		obj.Set("clientHandshake", o.ClientHandshake)
	}
	if o.ServerHandshake != "" {
		obj.Set("serverHandshake", o.ServerHandshake)
	}
	if o.ClientFinished != "" {
		obj.Set("clientFinished", o.ClientFinished)
	}
	if o.ServerFinished != "" {
		obj.Set("serverFinished", o.ServerFinished)
	}
	return obj
}

// IncomingRequestCFPropertiesEdgeRequestKeepAliveStatus An upstream endpoint's response to a TCP `keepalive` message from Cloudflare.
type IncomingRequestCFPropertiesEdgeRequestKeepAliveStatus = int
