// Code generated by cfgen from @cloudflare/workers-types@5.20260906.1. DO NOT EDIT.

//go:build js && wasm

// Package analytics provides the Analytics Engine binding
// (https://developers.cloudflare.com/analytics/analytics-engine/).
package analytics

import (
	"syscall/js"

	"github.com/syumai/workers-go/exp/internal/jsrt"
)

// AnalyticsEngineDataset
type AnalyticsEngineDataset struct{ v js.Value }

// AnalyticsEngineDatasetFromJS wraps a JS AnalyticsEngineDataset value.
func AnalyticsEngineDatasetFromJS(v js.Value) *AnalyticsEngineDataset {
	return &AnalyticsEngineDataset{v: v}
}

// JSValue returns the underlying JS value.
func (x *AnalyticsEngineDataset) JSValue() js.Value { return x.v }

// NewAnalyticsEngineDataset resolves the binding named bindingName from env.
func NewAnalyticsEngineDataset(bindingName string) (*AnalyticsEngineDataset, error) {
	v, err := jsrt.Binding(bindingName)
	if err != nil {
		return nil, err
	}
	return &AnalyticsEngineDataset{v: v}, nil
}

// WriteDataPoint
func (x *AnalyticsEngineDataset) WriteDataPoint(event AnalyticsEngineDataPoint) error {
	_, err := jsrt.Call(x.v, "writeDataPoint", event.toJS())
	return err
}

// AnalyticsEngineDataPoint
type AnalyticsEngineDataPoint struct {
	Indexes []string  `js:"indexes"`
	Doubles []float64 `js:"doubles"`
	Blobs   []string  `js:"blobs"`
}

func analyticsEngineDataPointFromJS(v js.Value) (AnalyticsEngineDataPoint, error) {
	var out AnalyticsEngineDataPoint
	{
		if s := v.Get("indexes"); !s.IsUndefined() && !s.IsNull() {
			out.Indexes = make([]string, s.Length())
			for i := range out.Indexes {
				out.Indexes[i] = s.Index(i).String()
			}
		}
	}
	{
		if s := v.Get("doubles"); !s.IsUndefined() && !s.IsNull() {
			out.Doubles = make([]float64, s.Length())
			for i := range out.Doubles {
				out.Doubles[i] = s.Index(i).Float()
			}
		}
	}
	{
		if s := v.Get("blobs"); !s.IsUndefined() && !s.IsNull() {
			out.Blobs = make([]string, s.Length())
			for i := range out.Blobs {
				out.Blobs[i] = s.Index(i).String()
			}
		}
	}
	return out, nil
}

func (o AnalyticsEngineDataPoint) toJS() js.Value {
	obj := jsrt.NewObject()
	if len(o.Indexes) > 0 {
		arr := js.Global().Get("Array").New(len(o.Indexes))
		for i, e := range o.Indexes {
			arr.SetIndex(i, e)
		}
		obj.Set("indexes", arr)
	}
	if len(o.Doubles) > 0 {
		arr := js.Global().Get("Array").New(len(o.Doubles))
		for i, e := range o.Doubles {
			arr.SetIndex(i, e)
		}
		obj.Set("doubles", arr)
	}
	if len(o.Blobs) > 0 {
		arr := js.Global().Get("Array").New(len(o.Blobs))
		for i, e := range o.Blobs {
			arr.SetIndex(i, e)
		}
		obj.Set("blobs", arr)
	}
	return obj
}
